version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    generated: strict
    paths:
      - gen
      - internal/infrastructure/postgres/models
      - dberrors
      - dbinfo
      - factory
      - models
