version: '3'

dotenv: ['.env']

vars:
  BINARY_NAME: kin-api
  BUILD_DIR: ./bin
  MAIN_PATH: ./cmd/api
  MIGRATIONS_DIR: ./internal/infrastructure/postgres/migrations
  ENV: '{{.ENV | default "development"}}'
  VERSION: '{{.VERSION | default "dev"}}'
  GIT_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILD_TIME:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  LDFLAGS: -s -w -X main.Version={{.VERSION}} -X main.GitCommit={{.GIT_COMMIT}} -X main.BuildTime={{.BUILD_TIME}}

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  ## Setup

  setup:
    desc: Install development dependencies and setup local config
    deps: [bob:install, deps]
    cmds:
      - task: config:init

  config:init:
    desc: Initialize local config from template
    status:
      - test -f config/config.development.yaml
    cmds:
      - echo "Creating local development config..."
      - cp config/config.development.yaml.example config/config.development.yaml
      - echo "Created config/config.development.yaml - customize as needed"

  ## Build

  build:
    desc: Build the application
    cmds:
      - echo "Building {{.BINARY_NAME}} (version={{.VERSION}}, commit={{.GIT_COMMIT}})..."
      - mkdir -p {{.BUILD_DIR}}
      - go build -ldflags "{{.LDFLAGS}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PATH}}

  run:
    desc: Run the application
    cmds:
      - echo "Running {{.BINARY_NAME}}..."
      - KIN_ENV={{.ENV}} go run {{.MAIN_PATH}}/main.go

  dev:
    desc: Run with hot reload (air)
    cmds:
      - echo "Starting development server with hot reload..."
      - air

  ## Testing

  test:
    desc: Run tests
    cmds:
      - echo "Running tests..."
      - go test -v -race -cover ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - echo "Running tests with coverage..."
      - go test -v -race -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  ## Formatting

  format:
    desc: Format code and fix lint issues
    cmds:
      - echo "Formatting Go code..."
      - find . -name '*.go' -not -path './gen/*' -not -path './internal/infrastructure/postgres/models/*' | xargs gofmt -s -w
      - find . -name '*.go' -not -path './gen/*' -not -path './internal/infrastructure/postgres/models/*' | xargs goimports -w
      - echo "Formatting proto files..."
      - buf format -w
      - echo "Fixing lint issues..."
      - golangci-lint run --fix ./...
      - echo "Formatting complete."

  ## Linting

  lint:
    desc: Run linter
    cmds:
      - echo "Running linter..."
      - golangci-lint run ./...

  ## Dependencies

  deps:
    desc: Download dependencies
    cmds:
      - echo "Downloading dependencies..."
      - go mod download

  tidy:
    desc: Tidy dependencies
    cmds:
      - echo "Tidying dependencies..."
      - go mod tidy

  ## Docker

  docker:up:
    desc: Start Docker containers
    cmds:
      - echo "Starting Docker containers..."
      - docker-compose up -d

  docker:down:
    desc: Stop Docker containers
    cmds:
      - echo "Stopping Docker containers..."
      - docker-compose down

  docker:logs:
    desc: Show Docker logs
    cmds:
      - echo "Showing Docker logs..."
      - docker-compose logs -f

  docker:build:
    desc: Build Docker image
    cmds:
      - echo "Building Docker image..."
      - docker build -t {{.BINARY_NAME}}:latest .

  ## Database Migrations (pgroll)

  migrate:init:
    desc: Initialize pgroll in the database
    cmds:
      - echo "Initializing pgroll..."
      - pgroll --postgres-url "$DATABASE_WRITE_URL" init

  migrate:new:
    desc: Create a new migration file (task migrate:new NAME="create foo")
    cmds:
      - |
        TIMESTAMP=$(date +"%Y%m%d%H%M%S")
        SAFE_NAME=$(echo "{{.NAME}}" | tr ' ' '_')
        FILENAME="${TIMESTAMP}_${SAFE_NAME}.json"
        pgroll create --empty --json --name "${SAFE_NAME}" > {{.MIGRATIONS_DIR}}/$FILENAME
        echo "Created migration: {{.MIGRATIONS_DIR}}/$FILENAME"
    requires:
      vars: [NAME]

  migrate:up:
    desc: Run all migrations
    cmds:
      - echo "Checking pgroll status..."
      - |
        if ! pgroll --postgres-url "$DATABASE_WRITE_URL" status > /dev/null 2>&1; then
          echo "pgroll not initialized, initializing..."
          pgroll --postgres-url "$DATABASE_WRITE_URL" init
        fi
      - echo "Running all migrations..."
      - pgroll --postgres-url "$DATABASE_WRITE_URL" migrate --complete {{.MIGRATIONS_DIR}}

  migrate:start:
    desc: Start a specific migration (task migrate:start FILE=xxx.json)
    cmds:
      - echo "Starting migration {{.FILE}}..."
      - pgroll --postgres-url "$DATABASE_WRITE_URL" start {{.MIGRATIONS_DIR}}/{{.FILE}}
    requires:
      vars: [FILE]

  migrate:complete:
    desc: Complete current migration
    cmds:
      - echo "Completing migration..."
      - pgroll --postgres-url "$DATABASE_WRITE_URL" complete

  migrate:rollback:
    desc: Rollback current migration
    cmds:
      - echo "Rolling back migration..."
      - pgroll --postgres-url "$DATABASE_WRITE_URL" rollback

  migrate:status:
    desc: Show migration status
    cmds:
      - echo "Migration status..."
      - pgroll --postgres-url "$DATABASE_WRITE_URL" status

  ## Code Generation

  generate:
    desc: Generate all code (protobuf, gRPC, Bob models)
    cmds:
      - task: proto:generate
      - task: bob:generate

  proto:generate:
    desc: Generate protobuf and gRPC code
    cmds:
      - echo "Generating protobuf and gRPC code..."
      - buf generate

  proto:lint:
    desc: Lint proto files
    cmds:
      - echo "Linting proto files..."
      - buf lint

  proto:breaking:
    desc: Check for breaking changes in proto files
    cmds:
      - echo "Checking for breaking changes..."
      - buf breaking --against '.git#branch=main'

  proto:format:
    desc: Format proto files
    cmds:
      - echo "Formatting proto files..."
      - buf format -w

  ## Bob Code Generation

  bob:install:
    desc: Install bobgen-psql
    status:
      - test -f ${GOBIN:-$HOME/go/bin}/bobgen-psql
    cmds:
      - go install github.com/stephenafamo/bob/gen/bobgen-psql@v0.42.0

  bob:generate:
    desc: Generate Bob models
    deps: [bob:install]
    cmds:
      - echo "Generating Bob models..."
      - PSQL_DSN="$DATABASE_WRITE_URL" bobgen-psql

  ## Clean

  clean:
    desc: Clean build artifacts
    cmds:
      - echo "Cleaning..."
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html
