// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	models "github.com/danielng/kin-core-svc/models"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type CircleMemberMod interface {
	Apply(context.Context, *CircleMemberTemplate)
}

type CircleMemberModFunc func(context.Context, *CircleMemberTemplate)

func (f CircleMemberModFunc) Apply(ctx context.Context, n *CircleMemberTemplate) {
	f(ctx, n)
}

type CircleMemberModSlice []CircleMemberMod

func (mods CircleMemberModSlice) Apply(ctx context.Context, n *CircleMemberTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// CircleMemberTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type CircleMemberTemplate struct {
	ID        func() uuid.UUID
	CircleID  func() uuid.UUID
	UserID    func() uuid.UUID
	Role      func() string
	Nickname  func() null.Val[string]
	JoinedAt  func() time.Time
	UpdatedAt func() time.Time

	r circleMemberR
	f *Factory

	alreadyPersisted bool
}

type circleMemberR struct {
	Circle *circleMemberRCircleR
	User   *circleMemberRUserR
}

type circleMemberRCircleR struct {
	o *CircleTemplate
}
type circleMemberRUserR struct {
	o *UserTemplate
}

// Apply mods to the CircleMemberTemplate
func (o *CircleMemberTemplate) Apply(ctx context.Context, mods ...CircleMemberMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.CircleMember
// according to the relationships in the template. Nothing is inserted into the db
func (t CircleMemberTemplate) setModelRels(o *models.CircleMember) {
	if t.r.Circle != nil {
		rel := t.r.Circle.o.Build()
		rel.R.CircleMembers = append(rel.R.CircleMembers, o)
		o.CircleID = rel.ID // h2
		o.R.Circle = rel
	}

	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.CircleMembers = append(rel.R.CircleMembers, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.CircleMemberSetter
// this does nothing with the relationship templates
func (o CircleMemberTemplate) BuildSetter() *models.CircleMemberSetter {
	m := &models.CircleMemberSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.CircleID != nil {
		val := o.CircleID()
		m.CircleID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.Role != nil {
		val := o.Role()
		m.Role = omit.From(val)
	}
	if o.Nickname != nil {
		val := o.Nickname()
		m.Nickname = omitnull.FromNull(val)
	}
	if o.JoinedAt != nil {
		val := o.JoinedAt()
		m.JoinedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.CircleMemberSetter
// this does nothing with the relationship templates
func (o CircleMemberTemplate) BuildManySetter(number int) []*models.CircleMemberSetter {
	m := make([]*models.CircleMemberSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.CircleMember
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CircleMemberTemplate.Create
func (o CircleMemberTemplate) Build() *models.CircleMember {
	m := &models.CircleMember{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.CircleID != nil {
		m.CircleID = o.CircleID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.Role != nil {
		m.Role = o.Role()
	}
	if o.Nickname != nil {
		m.Nickname = o.Nickname()
	}
	if o.JoinedAt != nil {
		m.JoinedAt = o.JoinedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.CircleMemberSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CircleMemberTemplate.CreateMany
func (o CircleMemberTemplate) BuildMany(number int) models.CircleMemberSlice {
	m := make(models.CircleMemberSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableCircleMember(m *models.CircleMemberSetter) {
	if !(m.ID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if !(m.CircleID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.CircleID = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.UserID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.CircleMember
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *CircleMemberTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.CircleMember) error {
	var err error

	return err
}

// Create builds a circleMember and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *CircleMemberTemplate) Create(ctx context.Context, exec bob.Executor) (*models.CircleMember, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableCircleMember(opt)

	if o.r.Circle == nil {
		CircleMemberMods.WithNewCircle().Apply(ctx, o)
	}

	var rel0 *models.Circle

	if o.r.Circle.o.alreadyPersisted {
		rel0 = o.r.Circle.o.Build()
	} else {
		rel0, err = o.r.Circle.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.CircleID = omit.From(rel0.ID)

	if o.r.User == nil {
		CircleMemberMods.WithNewUser().Apply(ctx, o)
	}

	var rel1 *models.User

	if o.r.User.o.alreadyPersisted {
		rel1 = o.r.User.o.Build()
	} else {
		rel1, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel1.ID)

	m, err := models.CircleMembers.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Circle = rel0
	m.R.User = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a circleMember and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *CircleMemberTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.CircleMember {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a circleMember and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *CircleMemberTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.CircleMember {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple circleMembers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o CircleMemberTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.CircleMemberSlice, error) {
	var err error
	m := make(models.CircleMemberSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple circleMembers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o CircleMemberTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.CircleMemberSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple circleMembers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o CircleMemberTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.CircleMemberSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CircleMember has methods that act as mods for the CircleMemberTemplate
var CircleMemberMods circleMemberMods

type circleMemberMods struct{}

func (m circleMemberMods) RandomizeAllColumns(f *faker.Faker) CircleMemberMod {
	return CircleMemberModSlice{
		CircleMemberMods.RandomID(f),
		CircleMemberMods.RandomCircleID(f),
		CircleMemberMods.RandomUserID(f),
		CircleMemberMods.RandomRole(f),
		CircleMemberMods.RandomNickname(f),
		CircleMemberMods.RandomJoinedAt(f),
		CircleMemberMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m circleMemberMods) ID(val uuid.UUID) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m circleMemberMods) IDFunc(f func() uuid.UUID) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m circleMemberMods) UnsetID() CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m circleMemberMods) RandomID(f *faker.Faker) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m circleMemberMods) CircleID(val uuid.UUID) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.CircleID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m circleMemberMods) CircleIDFunc(f func() uuid.UUID) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.CircleID = f
	})
}

// Clear any values for the column
func (m circleMemberMods) UnsetCircleID() CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.CircleID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m circleMemberMods) RandomCircleID(f *faker.Faker) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.CircleID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m circleMemberMods) UserID(val uuid.UUID) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.UserID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m circleMemberMods) UserIDFunc(f func() uuid.UUID) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m circleMemberMods) UnsetUserID() CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m circleMemberMods) RandomUserID(f *faker.Faker) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.UserID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m circleMemberMods) Role(val string) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.Role = func() string { return val }
	})
}

// Set the Column from the function
func (m circleMemberMods) RoleFunc(f func() string) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.Role = f
	})
}

// Clear any values for the column
func (m circleMemberMods) UnsetRole() CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.Role = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m circleMemberMods) RandomRole(f *faker.Faker) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.Role = func() string {
			return random_string(f, "20")
		}
	})
}

// Set the model columns to this value
func (m circleMemberMods) Nickname(val null.Val[string]) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.Nickname = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m circleMemberMods) NicknameFunc(f func() null.Val[string]) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.Nickname = f
	})
}

// Clear any values for the column
func (m circleMemberMods) UnsetNickname() CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.Nickname = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m circleMemberMods) RandomNickname(f *faker.Faker) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.Nickname = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "100")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m circleMemberMods) RandomNicknameNotNull(f *faker.Faker) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.Nickname = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "100")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m circleMemberMods) JoinedAt(val time.Time) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.JoinedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m circleMemberMods) JoinedAtFunc(f func() time.Time) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.JoinedAt = f
	})
}

// Clear any values for the column
func (m circleMemberMods) UnsetJoinedAt() CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.JoinedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m circleMemberMods) RandomJoinedAt(f *faker.Faker) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.JoinedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m circleMemberMods) UpdatedAt(val time.Time) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m circleMemberMods) UpdatedAtFunc(f func() time.Time) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m circleMemberMods) UnsetUpdatedAt() CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m circleMemberMods) RandomUpdatedAt(f *faker.Faker) CircleMemberMod {
	return CircleMemberModFunc(func(_ context.Context, o *CircleMemberTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m circleMemberMods) WithParentsCascading() CircleMemberMod {
	return CircleMemberModFunc(func(ctx context.Context, o *CircleMemberTemplate) {
		if isDone, _ := circleMemberWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = circleMemberWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewCircleWithContext(ctx, CircleMods.WithParentsCascading())
			m.WithCircle(related).Apply(ctx, o)
		}
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m circleMemberMods) WithCircle(rel *CircleTemplate) CircleMemberMod {
	return CircleMemberModFunc(func(ctx context.Context, o *CircleMemberTemplate) {
		o.r.Circle = &circleMemberRCircleR{
			o: rel,
		}
	})
}

func (m circleMemberMods) WithNewCircle(mods ...CircleMod) CircleMemberMod {
	return CircleMemberModFunc(func(ctx context.Context, o *CircleMemberTemplate) {
		related := o.f.NewCircleWithContext(ctx, mods...)

		m.WithCircle(related).Apply(ctx, o)
	})
}

func (m circleMemberMods) WithExistingCircle(em *models.Circle) CircleMemberMod {
	return CircleMemberModFunc(func(ctx context.Context, o *CircleMemberTemplate) {
		o.r.Circle = &circleMemberRCircleR{
			o: o.f.FromExistingCircle(em),
		}
	})
}

func (m circleMemberMods) WithoutCircle() CircleMemberMod {
	return CircleMemberModFunc(func(ctx context.Context, o *CircleMemberTemplate) {
		o.r.Circle = nil
	})
}

func (m circleMemberMods) WithUser(rel *UserTemplate) CircleMemberMod {
	return CircleMemberModFunc(func(ctx context.Context, o *CircleMemberTemplate) {
		o.r.User = &circleMemberRUserR{
			o: rel,
		}
	})
}

func (m circleMemberMods) WithNewUser(mods ...UserMod) CircleMemberMod {
	return CircleMemberModFunc(func(ctx context.Context, o *CircleMemberTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m circleMemberMods) WithExistingUser(em *models.User) CircleMemberMod {
	return CircleMemberModFunc(func(ctx context.Context, o *CircleMemberTemplate) {
		o.r.User = &circleMemberRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m circleMemberMods) WithoutUser() CircleMemberMod {
	return CircleMemberModFunc(func(ctx context.Context, o *CircleMemberTemplate) {
		o.r.User = nil
	})
}
