// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	models "github.com/danielng/kin-core-svc/models"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type ContactMod interface {
	Apply(context.Context, *ContactTemplate)
}

type ContactModFunc func(context.Context, *ContactTemplate)

func (f ContactModFunc) Apply(ctx context.Context, n *ContactTemplate) {
	f(ctx, n)
}

type ContactModSlice []ContactMod

func (mods ContactModSlice) Apply(ctx context.Context, n *ContactTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ContactTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ContactTemplate struct {
	ID         func() uuid.UUID
	UserID     func() uuid.UUID
	ContactID  func() uuid.UUID
	Nickname   func() null.Val[string]
	IsFavorite func() bool
	IsBlocked  func() bool
	CreatedAt  func() time.Time
	UpdatedAt  func() time.Time

	r contactR
	f *Factory

	alreadyPersisted bool
}

type contactR struct {
	ContactUser *contactRContactUserR
	User        *contactRUserR
}

type contactRContactUserR struct {
	o *UserTemplate
}
type contactRUserR struct {
	o *UserTemplate
}

// Apply mods to the ContactTemplate
func (o *ContactTemplate) Apply(ctx context.Context, mods ...ContactMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Contact
// according to the relationships in the template. Nothing is inserted into the db
func (t ContactTemplate) setModelRels(o *models.Contact) {
	if t.r.ContactUser != nil {
		rel := t.r.ContactUser.o.Build()
		rel.R.ContactContacts = append(rel.R.ContactContacts, o)
		o.ContactID = rel.ID // h2
		o.R.ContactUser = rel
	}

	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.Contacts = append(rel.R.Contacts, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.ContactSetter
// this does nothing with the relationship templates
func (o ContactTemplate) BuildSetter() *models.ContactSetter {
	m := &models.ContactSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.ContactID != nil {
		val := o.ContactID()
		m.ContactID = omit.From(val)
	}
	if o.Nickname != nil {
		val := o.Nickname()
		m.Nickname = omitnull.FromNull(val)
	}
	if o.IsFavorite != nil {
		val := o.IsFavorite()
		m.IsFavorite = omit.From(val)
	}
	if o.IsBlocked != nil {
		val := o.IsBlocked()
		m.IsBlocked = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ContactSetter
// this does nothing with the relationship templates
func (o ContactTemplate) BuildManySetter(number int) []*models.ContactSetter {
	m := make([]*models.ContactSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Contact
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ContactTemplate.Create
func (o ContactTemplate) Build() *models.Contact {
	m := &models.Contact{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.ContactID != nil {
		m.ContactID = o.ContactID()
	}
	if o.Nickname != nil {
		m.Nickname = o.Nickname()
	}
	if o.IsFavorite != nil {
		m.IsFavorite = o.IsFavorite()
	}
	if o.IsBlocked != nil {
		m.IsBlocked = o.IsBlocked()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ContactSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ContactTemplate.CreateMany
func (o ContactTemplate) BuildMany(number int) models.ContactSlice {
	m := make(models.ContactSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableContact(m *models.ContactSetter) {
	if !(m.ID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.UserID = omit.From(val)
	}
	if !(m.ContactID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ContactID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Contact
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ContactTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Contact) error {
	var err error

	return err
}

// Create builds a contact and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ContactTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Contact, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableContact(opt)

	if o.r.ContactUser == nil {
		ContactMods.WithNewContactUser().Apply(ctx, o)
	}

	var rel0 *models.User

	if o.r.ContactUser.o.alreadyPersisted {
		rel0 = o.r.ContactUser.o.Build()
	} else {
		rel0, err = o.r.ContactUser.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.ContactID = omit.From(rel0.ID)

	if o.r.User == nil {
		ContactMods.WithNewUser().Apply(ctx, o)
	}

	var rel1 *models.User

	if o.r.User.o.alreadyPersisted {
		rel1 = o.r.User.o.Build()
	} else {
		rel1, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel1.ID)

	m, err := models.Contacts.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.ContactUser = rel0
	m.R.User = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a contact and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ContactTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Contact {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a contact and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ContactTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Contact {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple contacts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ContactTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ContactSlice, error) {
	var err error
	m := make(models.ContactSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple contacts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ContactTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ContactSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple contacts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ContactTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ContactSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Contact has methods that act as mods for the ContactTemplate
var ContactMods contactMods

type contactMods struct{}

func (m contactMods) RandomizeAllColumns(f *faker.Faker) ContactMod {
	return ContactModSlice{
		ContactMods.RandomID(f),
		ContactMods.RandomUserID(f),
		ContactMods.RandomContactID(f),
		ContactMods.RandomNickname(f),
		ContactMods.RandomIsFavorite(f),
		ContactMods.RandomIsBlocked(f),
		ContactMods.RandomCreatedAt(f),
		ContactMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m contactMods) ID(val uuid.UUID) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m contactMods) IDFunc(f func() uuid.UUID) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m contactMods) UnsetID() ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m contactMods) RandomID(f *faker.Faker) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m contactMods) UserID(val uuid.UUID) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.UserID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m contactMods) UserIDFunc(f func() uuid.UUID) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m contactMods) UnsetUserID() ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m contactMods) RandomUserID(f *faker.Faker) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.UserID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m contactMods) ContactID(val uuid.UUID) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.ContactID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m contactMods) ContactIDFunc(f func() uuid.UUID) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.ContactID = f
	})
}

// Clear any values for the column
func (m contactMods) UnsetContactID() ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.ContactID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m contactMods) RandomContactID(f *faker.Faker) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.ContactID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m contactMods) Nickname(val null.Val[string]) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.Nickname = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m contactMods) NicknameFunc(f func() null.Val[string]) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.Nickname = f
	})
}

// Clear any values for the column
func (m contactMods) UnsetNickname() ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.Nickname = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m contactMods) RandomNickname(f *faker.Faker) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.Nickname = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "100")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m contactMods) RandomNicknameNotNull(f *faker.Faker) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.Nickname = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "100")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m contactMods) IsFavorite(val bool) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.IsFavorite = func() bool { return val }
	})
}

// Set the Column from the function
func (m contactMods) IsFavoriteFunc(f func() bool) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.IsFavorite = f
	})
}

// Clear any values for the column
func (m contactMods) UnsetIsFavorite() ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.IsFavorite = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m contactMods) RandomIsFavorite(f *faker.Faker) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.IsFavorite = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m contactMods) IsBlocked(val bool) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.IsBlocked = func() bool { return val }
	})
}

// Set the Column from the function
func (m contactMods) IsBlockedFunc(f func() bool) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.IsBlocked = f
	})
}

// Clear any values for the column
func (m contactMods) UnsetIsBlocked() ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.IsBlocked = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m contactMods) RandomIsBlocked(f *faker.Faker) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.IsBlocked = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m contactMods) CreatedAt(val time.Time) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m contactMods) CreatedAtFunc(f func() time.Time) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m contactMods) UnsetCreatedAt() ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m contactMods) RandomCreatedAt(f *faker.Faker) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m contactMods) UpdatedAt(val time.Time) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m contactMods) UpdatedAtFunc(f func() time.Time) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m contactMods) UnsetUpdatedAt() ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m contactMods) RandomUpdatedAt(f *faker.Faker) ContactMod {
	return ContactModFunc(func(_ context.Context, o *ContactTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m contactMods) WithParentsCascading() ContactMod {
	return ContactModFunc(func(ctx context.Context, o *ContactTemplate) {
		if isDone, _ := contactWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = contactWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithContactUser(related).Apply(ctx, o)
		}
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m contactMods) WithContactUser(rel *UserTemplate) ContactMod {
	return ContactModFunc(func(ctx context.Context, o *ContactTemplate) {
		o.r.ContactUser = &contactRContactUserR{
			o: rel,
		}
	})
}

func (m contactMods) WithNewContactUser(mods ...UserMod) ContactMod {
	return ContactModFunc(func(ctx context.Context, o *ContactTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithContactUser(related).Apply(ctx, o)
	})
}

func (m contactMods) WithExistingContactUser(em *models.User) ContactMod {
	return ContactModFunc(func(ctx context.Context, o *ContactTemplate) {
		o.r.ContactUser = &contactRContactUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m contactMods) WithoutContactUser() ContactMod {
	return ContactModFunc(func(ctx context.Context, o *ContactTemplate) {
		o.r.ContactUser = nil
	})
}

func (m contactMods) WithUser(rel *UserTemplate) ContactMod {
	return ContactModFunc(func(ctx context.Context, o *ContactTemplate) {
		o.r.User = &contactRUserR{
			o: rel,
		}
	})
}

func (m contactMods) WithNewUser(mods ...UserMod) ContactMod {
	return ContactModFunc(func(ctx context.Context, o *ContactTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m contactMods) WithExistingUser(em *models.User) ContactMod {
	return ContactModFunc(func(ctx context.Context, o *ContactTemplate) {
		o.r.User = &contactRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m contactMods) WithoutUser() ContactMod {
	return ContactModFunc(func(ctx context.Context, o *ContactTemplate) {
		o.r.User = nil
	})
}
