// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	models "github.com/danielng/kin-core-svc/models"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type ConversationMod interface {
	Apply(context.Context, *ConversationTemplate)
}

type ConversationModFunc func(context.Context, *ConversationTemplate)

func (f ConversationModFunc) Apply(ctx context.Context, n *ConversationTemplate) {
	f(ctx, n)
}

type ConversationModSlice []ConversationMod

func (mods ConversationModSlice) Apply(ctx context.Context, n *ConversationTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ConversationTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ConversationTemplate struct {
	ID            func() uuid.UUID
	Type          func() string
	CircleID      func() null.Val[uuid.UUID]
	Name          func() null.Val[string]
	Avatar        func() null.Val[string]
	LastMessageID func() null.Val[uuid.UUID]
	LastMessageAt func() null.Val[time.Time]
	CreatedAt     func() time.Time
	UpdatedAt     func() time.Time

	r conversationR
	f *Factory

	alreadyPersisted bool
}

type conversationR struct {
	ConversationParticipants []*conversationRConversationParticipantsR
	Circle                   *conversationRCircleR
	Messages                 []*conversationRMessagesR
}

type conversationRConversationParticipantsR struct {
	number int
	o      *ConversationParticipantTemplate
}
type conversationRCircleR struct {
	o *CircleTemplate
}
type conversationRMessagesR struct {
	number int
	o      *MessageTemplate
}

// Apply mods to the ConversationTemplate
func (o *ConversationTemplate) Apply(ctx context.Context, mods ...ConversationMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Conversation
// according to the relationships in the template. Nothing is inserted into the db
func (t ConversationTemplate) setModelRels(o *models.Conversation) {
	if t.r.ConversationParticipants != nil {
		rel := models.ConversationParticipantSlice{}
		for _, r := range t.r.ConversationParticipants {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ConversationID = o.ID // h2
				rel.R.Conversation = o
			}
			rel = append(rel, related...)
		}
		o.R.ConversationParticipants = rel
	}

	if t.r.Circle != nil {
		rel := t.r.Circle.o.Build()
		rel.R.Conversations = append(rel.R.Conversations, o)
		o.CircleID = null.From(rel.ID) // h2
		o.R.Circle = rel
	}

	if t.r.Messages != nil {
		rel := models.MessageSlice{}
		for _, r := range t.r.Messages {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ConversationID = o.ID // h2
				rel.R.Conversation = o
			}
			rel = append(rel, related...)
		}
		o.R.Messages = rel
	}
}

// BuildSetter returns an *models.ConversationSetter
// this does nothing with the relationship templates
func (o ConversationTemplate) BuildSetter() *models.ConversationSetter {
	m := &models.ConversationSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Type != nil {
		val := o.Type()
		m.Type = omit.From(val)
	}
	if o.CircleID != nil {
		val := o.CircleID()
		m.CircleID = omitnull.FromNull(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omitnull.FromNull(val)
	}
	if o.Avatar != nil {
		val := o.Avatar()
		m.Avatar = omitnull.FromNull(val)
	}
	if o.LastMessageID != nil {
		val := o.LastMessageID()
		m.LastMessageID = omitnull.FromNull(val)
	}
	if o.LastMessageAt != nil {
		val := o.LastMessageAt()
		m.LastMessageAt = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ConversationSetter
// this does nothing with the relationship templates
func (o ConversationTemplate) BuildManySetter(number int) []*models.ConversationSetter {
	m := make([]*models.ConversationSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Conversation
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ConversationTemplate.Create
func (o ConversationTemplate) Build() *models.Conversation {
	m := &models.Conversation{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Type != nil {
		m.Type = o.Type()
	}
	if o.CircleID != nil {
		m.CircleID = o.CircleID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Avatar != nil {
		m.Avatar = o.Avatar()
	}
	if o.LastMessageID != nil {
		m.LastMessageID = o.LastMessageID()
	}
	if o.LastMessageAt != nil {
		m.LastMessageAt = o.LastMessageAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ConversationSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ConversationTemplate.CreateMany
func (o ConversationTemplate) BuildMany(number int) models.ConversationSlice {
	m := make(models.ConversationSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableConversation(m *models.ConversationSetter) {
	if !(m.ID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if !(m.Type.IsValue()) {
		val := random_string(nil, "20")
		m.Type = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Conversation
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ConversationTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Conversation) error {
	var err error

	isConversationParticipantsDone, _ := conversationRelConversationParticipantsCtx.Value(ctx)
	if !isConversationParticipantsDone && o.r.ConversationParticipants != nil {
		ctx = conversationRelConversationParticipantsCtx.WithValue(ctx, true)
		for _, r := range o.r.ConversationParticipants {
			if r.o.alreadyPersisted {
				m.R.ConversationParticipants = append(m.R.ConversationParticipants, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachConversationParticipants(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isCircleDone, _ := conversationRelCircleCtx.Value(ctx)
	if !isCircleDone && o.r.Circle != nil {
		ctx = conversationRelCircleCtx.WithValue(ctx, true)
		if o.r.Circle.o.alreadyPersisted {
			m.R.Circle = o.r.Circle.o.Build()
		} else {
			var rel1 *models.Circle
			rel1, err = o.r.Circle.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachCircle(ctx, exec, rel1)
			if err != nil {
				return err
			}
		}

	}

	isMessagesDone, _ := conversationRelMessagesCtx.Value(ctx)
	if !isMessagesDone && o.r.Messages != nil {
		ctx = conversationRelMessagesCtx.WithValue(ctx, true)
		for _, r := range o.r.Messages {
			if r.o.alreadyPersisted {
				m.R.Messages = append(m.R.Messages, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachMessages(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a conversation and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ConversationTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Conversation, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableConversation(opt)

	m, err := models.Conversations.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a conversation and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ConversationTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Conversation {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a conversation and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ConversationTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Conversation {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple conversations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ConversationTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ConversationSlice, error) {
	var err error
	m := make(models.ConversationSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple conversations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ConversationTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ConversationSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple conversations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ConversationTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ConversationSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Conversation has methods that act as mods for the ConversationTemplate
var ConversationMods conversationMods

type conversationMods struct{}

func (m conversationMods) RandomizeAllColumns(f *faker.Faker) ConversationMod {
	return ConversationModSlice{
		ConversationMods.RandomID(f),
		ConversationMods.RandomType(f),
		ConversationMods.RandomCircleID(f),
		ConversationMods.RandomName(f),
		ConversationMods.RandomAvatar(f),
		ConversationMods.RandomLastMessageID(f),
		ConversationMods.RandomLastMessageAt(f),
		ConversationMods.RandomCreatedAt(f),
		ConversationMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m conversationMods) ID(val uuid.UUID) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m conversationMods) IDFunc(f func() uuid.UUID) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m conversationMods) UnsetID() ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m conversationMods) RandomID(f *faker.Faker) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m conversationMods) Type(val string) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.Type = func() string { return val }
	})
}

// Set the Column from the function
func (m conversationMods) TypeFunc(f func() string) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.Type = f
	})
}

// Clear any values for the column
func (m conversationMods) UnsetType() ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.Type = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m conversationMods) RandomType(f *faker.Faker) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.Type = func() string {
			return random_string(f, "20")
		}
	})
}

// Set the model columns to this value
func (m conversationMods) CircleID(val null.Val[uuid.UUID]) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.CircleID = func() null.Val[uuid.UUID] { return val }
	})
}

// Set the Column from the function
func (m conversationMods) CircleIDFunc(f func() null.Val[uuid.UUID]) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.CircleID = f
	})
}

// Clear any values for the column
func (m conversationMods) UnsetCircleID() ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.CircleID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m conversationMods) RandomCircleID(f *faker.Faker) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.CircleID = func() null.Val[uuid.UUID] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_uuid_UUID(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m conversationMods) RandomCircleIDNotNull(f *faker.Faker) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.CircleID = func() null.Val[uuid.UUID] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_uuid_UUID(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m conversationMods) Name(val null.Val[string]) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.Name = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m conversationMods) NameFunc(f func() null.Val[string]) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m conversationMods) UnsetName() ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m conversationMods) RandomName(f *faker.Faker) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.Name = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "100")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m conversationMods) RandomNameNotNull(f *faker.Faker) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.Name = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "100")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m conversationMods) Avatar(val null.Val[string]) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.Avatar = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m conversationMods) AvatarFunc(f func() null.Val[string]) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.Avatar = f
	})
}

// Clear any values for the column
func (m conversationMods) UnsetAvatar() ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.Avatar = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m conversationMods) RandomAvatar(f *faker.Faker) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.Avatar = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m conversationMods) RandomAvatarNotNull(f *faker.Faker) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.Avatar = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m conversationMods) LastMessageID(val null.Val[uuid.UUID]) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.LastMessageID = func() null.Val[uuid.UUID] { return val }
	})
}

// Set the Column from the function
func (m conversationMods) LastMessageIDFunc(f func() null.Val[uuid.UUID]) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.LastMessageID = f
	})
}

// Clear any values for the column
func (m conversationMods) UnsetLastMessageID() ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.LastMessageID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m conversationMods) RandomLastMessageID(f *faker.Faker) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.LastMessageID = func() null.Val[uuid.UUID] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_uuid_UUID(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m conversationMods) RandomLastMessageIDNotNull(f *faker.Faker) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.LastMessageID = func() null.Val[uuid.UUID] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_uuid_UUID(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m conversationMods) LastMessageAt(val null.Val[time.Time]) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.LastMessageAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m conversationMods) LastMessageAtFunc(f func() null.Val[time.Time]) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.LastMessageAt = f
	})
}

// Clear any values for the column
func (m conversationMods) UnsetLastMessageAt() ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.LastMessageAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m conversationMods) RandomLastMessageAt(f *faker.Faker) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.LastMessageAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m conversationMods) RandomLastMessageAtNotNull(f *faker.Faker) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.LastMessageAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m conversationMods) CreatedAt(val time.Time) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m conversationMods) CreatedAtFunc(f func() time.Time) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m conversationMods) UnsetCreatedAt() ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m conversationMods) RandomCreatedAt(f *faker.Faker) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m conversationMods) UpdatedAt(val time.Time) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m conversationMods) UpdatedAtFunc(f func() time.Time) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m conversationMods) UnsetUpdatedAt() ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m conversationMods) RandomUpdatedAt(f *faker.Faker) ConversationMod {
	return ConversationModFunc(func(_ context.Context, o *ConversationTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m conversationMods) WithParentsCascading() ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		if isDone, _ := conversationWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = conversationWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewCircleWithContext(ctx, CircleMods.WithParentsCascading())
			m.WithCircle(related).Apply(ctx, o)
		}
	})
}

func (m conversationMods) WithCircle(rel *CircleTemplate) ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		o.r.Circle = &conversationRCircleR{
			o: rel,
		}
	})
}

func (m conversationMods) WithNewCircle(mods ...CircleMod) ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		related := o.f.NewCircleWithContext(ctx, mods...)

		m.WithCircle(related).Apply(ctx, o)
	})
}

func (m conversationMods) WithExistingCircle(em *models.Circle) ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		o.r.Circle = &conversationRCircleR{
			o: o.f.FromExistingCircle(em),
		}
	})
}

func (m conversationMods) WithoutCircle() ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		o.r.Circle = nil
	})
}

func (m conversationMods) WithConversationParticipants(number int, related *ConversationParticipantTemplate) ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		o.r.ConversationParticipants = []*conversationRConversationParticipantsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m conversationMods) WithNewConversationParticipants(number int, mods ...ConversationParticipantMod) ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		related := o.f.NewConversationParticipantWithContext(ctx, mods...)
		m.WithConversationParticipants(number, related).Apply(ctx, o)
	})
}

func (m conversationMods) AddConversationParticipants(number int, related *ConversationParticipantTemplate) ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		o.r.ConversationParticipants = append(o.r.ConversationParticipants, &conversationRConversationParticipantsR{
			number: number,
			o:      related,
		})
	})
}

func (m conversationMods) AddNewConversationParticipants(number int, mods ...ConversationParticipantMod) ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		related := o.f.NewConversationParticipantWithContext(ctx, mods...)
		m.AddConversationParticipants(number, related).Apply(ctx, o)
	})
}

func (m conversationMods) AddExistingConversationParticipants(existingModels ...*models.ConversationParticipant) ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		for _, em := range existingModels {
			o.r.ConversationParticipants = append(o.r.ConversationParticipants, &conversationRConversationParticipantsR{
				o: o.f.FromExistingConversationParticipant(em),
			})
		}
	})
}

func (m conversationMods) WithoutConversationParticipants() ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		o.r.ConversationParticipants = nil
	})
}

func (m conversationMods) WithMessages(number int, related *MessageTemplate) ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		o.r.Messages = []*conversationRMessagesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m conversationMods) WithNewMessages(number int, mods ...MessageMod) ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		related := o.f.NewMessageWithContext(ctx, mods...)
		m.WithMessages(number, related).Apply(ctx, o)
	})
}

func (m conversationMods) AddMessages(number int, related *MessageTemplate) ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		o.r.Messages = append(o.r.Messages, &conversationRMessagesR{
			number: number,
			o:      related,
		})
	})
}

func (m conversationMods) AddNewMessages(number int, mods ...MessageMod) ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		related := o.f.NewMessageWithContext(ctx, mods...)
		m.AddMessages(number, related).Apply(ctx, o)
	})
}

func (m conversationMods) AddExistingMessages(existingModels ...*models.Message) ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		for _, em := range existingModels {
			o.r.Messages = append(o.r.Messages, &conversationRMessagesR{
				o: o.f.FromExistingMessage(em),
			})
		}
	})
}

func (m conversationMods) WithoutMessages() ConversationMod {
	return ConversationModFunc(func(ctx context.Context, o *ConversationTemplate) {
		o.r.Messages = nil
	})
}
