// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	models "github.com/danielng/kin-core-svc/models"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type ConversationParticipantMod interface {
	Apply(context.Context, *ConversationParticipantTemplate)
}

type ConversationParticipantModFunc func(context.Context, *ConversationParticipantTemplate)

func (f ConversationParticipantModFunc) Apply(ctx context.Context, n *ConversationParticipantTemplate) {
	f(ctx, n)
}

type ConversationParticipantModSlice []ConversationParticipantMod

func (mods ConversationParticipantModSlice) Apply(ctx context.Context, n *ConversationParticipantTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ConversationParticipantTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ConversationParticipantTemplate struct {
	ID             func() uuid.UUID
	ConversationID func() uuid.UUID
	UserID         func() uuid.UUID
	IsMuted        func() bool
	IsArchived     func() bool
	LastReadAt     func() null.Val[time.Time]
	JoinedAt       func() time.Time
	LeftAt         func() null.Val[time.Time]
	UpdatedAt      func() time.Time

	r conversationParticipantR
	f *Factory

	alreadyPersisted bool
}

type conversationParticipantR struct {
	Conversation *conversationParticipantRConversationR
	User         *conversationParticipantRUserR
}

type conversationParticipantRConversationR struct {
	o *ConversationTemplate
}
type conversationParticipantRUserR struct {
	o *UserTemplate
}

// Apply mods to the ConversationParticipantTemplate
func (o *ConversationParticipantTemplate) Apply(ctx context.Context, mods ...ConversationParticipantMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.ConversationParticipant
// according to the relationships in the template. Nothing is inserted into the db
func (t ConversationParticipantTemplate) setModelRels(o *models.ConversationParticipant) {
	if t.r.Conversation != nil {
		rel := t.r.Conversation.o.Build()
		rel.R.ConversationParticipants = append(rel.R.ConversationParticipants, o)
		o.ConversationID = rel.ID // h2
		o.R.Conversation = rel
	}

	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.ConversationParticipants = append(rel.R.ConversationParticipants, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.ConversationParticipantSetter
// this does nothing with the relationship templates
func (o ConversationParticipantTemplate) BuildSetter() *models.ConversationParticipantSetter {
	m := &models.ConversationParticipantSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.ConversationID != nil {
		val := o.ConversationID()
		m.ConversationID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.IsMuted != nil {
		val := o.IsMuted()
		m.IsMuted = omit.From(val)
	}
	if o.IsArchived != nil {
		val := o.IsArchived()
		m.IsArchived = omit.From(val)
	}
	if o.LastReadAt != nil {
		val := o.LastReadAt()
		m.LastReadAt = omitnull.FromNull(val)
	}
	if o.JoinedAt != nil {
		val := o.JoinedAt()
		m.JoinedAt = omit.From(val)
	}
	if o.LeftAt != nil {
		val := o.LeftAt()
		m.LeftAt = omitnull.FromNull(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ConversationParticipantSetter
// this does nothing with the relationship templates
func (o ConversationParticipantTemplate) BuildManySetter(number int) []*models.ConversationParticipantSetter {
	m := make([]*models.ConversationParticipantSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.ConversationParticipant
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ConversationParticipantTemplate.Create
func (o ConversationParticipantTemplate) Build() *models.ConversationParticipant {
	m := &models.ConversationParticipant{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.ConversationID != nil {
		m.ConversationID = o.ConversationID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.IsMuted != nil {
		m.IsMuted = o.IsMuted()
	}
	if o.IsArchived != nil {
		m.IsArchived = o.IsArchived()
	}
	if o.LastReadAt != nil {
		m.LastReadAt = o.LastReadAt()
	}
	if o.JoinedAt != nil {
		m.JoinedAt = o.JoinedAt()
	}
	if o.LeftAt != nil {
		m.LeftAt = o.LeftAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ConversationParticipantSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ConversationParticipantTemplate.CreateMany
func (o ConversationParticipantTemplate) BuildMany(number int) models.ConversationParticipantSlice {
	m := make(models.ConversationParticipantSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableConversationParticipant(m *models.ConversationParticipantSetter) {
	if !(m.ID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if !(m.ConversationID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ConversationID = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.UserID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.ConversationParticipant
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ConversationParticipantTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.ConversationParticipant) error {
	var err error

	return err
}

// Create builds a conversationParticipant and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ConversationParticipantTemplate) Create(ctx context.Context, exec bob.Executor) (*models.ConversationParticipant, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableConversationParticipant(opt)

	if o.r.Conversation == nil {
		ConversationParticipantMods.WithNewConversation().Apply(ctx, o)
	}

	var rel0 *models.Conversation

	if o.r.Conversation.o.alreadyPersisted {
		rel0 = o.r.Conversation.o.Build()
	} else {
		rel0, err = o.r.Conversation.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.ConversationID = omit.From(rel0.ID)

	if o.r.User == nil {
		ConversationParticipantMods.WithNewUser().Apply(ctx, o)
	}

	var rel1 *models.User

	if o.r.User.o.alreadyPersisted {
		rel1 = o.r.User.o.Build()
	} else {
		rel1, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel1.ID)

	m, err := models.ConversationParticipants.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Conversation = rel0
	m.R.User = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a conversationParticipant and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ConversationParticipantTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.ConversationParticipant {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a conversationParticipant and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ConversationParticipantTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.ConversationParticipant {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple conversationParticipants and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ConversationParticipantTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ConversationParticipantSlice, error) {
	var err error
	m := make(models.ConversationParticipantSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple conversationParticipants and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ConversationParticipantTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ConversationParticipantSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple conversationParticipants and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ConversationParticipantTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ConversationParticipantSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// ConversationParticipant has methods that act as mods for the ConversationParticipantTemplate
var ConversationParticipantMods conversationParticipantMods

type conversationParticipantMods struct{}

func (m conversationParticipantMods) RandomizeAllColumns(f *faker.Faker) ConversationParticipantMod {
	return ConversationParticipantModSlice{
		ConversationParticipantMods.RandomID(f),
		ConversationParticipantMods.RandomConversationID(f),
		ConversationParticipantMods.RandomUserID(f),
		ConversationParticipantMods.RandomIsMuted(f),
		ConversationParticipantMods.RandomIsArchived(f),
		ConversationParticipantMods.RandomLastReadAt(f),
		ConversationParticipantMods.RandomJoinedAt(f),
		ConversationParticipantMods.RandomLeftAt(f),
		ConversationParticipantMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m conversationParticipantMods) ID(val uuid.UUID) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m conversationParticipantMods) IDFunc(f func() uuid.UUID) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m conversationParticipantMods) UnsetID() ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m conversationParticipantMods) RandomID(f *faker.Faker) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m conversationParticipantMods) ConversationID(val uuid.UUID) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.ConversationID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m conversationParticipantMods) ConversationIDFunc(f func() uuid.UUID) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.ConversationID = f
	})
}

// Clear any values for the column
func (m conversationParticipantMods) UnsetConversationID() ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.ConversationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m conversationParticipantMods) RandomConversationID(f *faker.Faker) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.ConversationID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m conversationParticipantMods) UserID(val uuid.UUID) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.UserID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m conversationParticipantMods) UserIDFunc(f func() uuid.UUID) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m conversationParticipantMods) UnsetUserID() ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m conversationParticipantMods) RandomUserID(f *faker.Faker) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.UserID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m conversationParticipantMods) IsMuted(val bool) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.IsMuted = func() bool { return val }
	})
}

// Set the Column from the function
func (m conversationParticipantMods) IsMutedFunc(f func() bool) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.IsMuted = f
	})
}

// Clear any values for the column
func (m conversationParticipantMods) UnsetIsMuted() ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.IsMuted = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m conversationParticipantMods) RandomIsMuted(f *faker.Faker) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.IsMuted = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m conversationParticipantMods) IsArchived(val bool) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.IsArchived = func() bool { return val }
	})
}

// Set the Column from the function
func (m conversationParticipantMods) IsArchivedFunc(f func() bool) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.IsArchived = f
	})
}

// Clear any values for the column
func (m conversationParticipantMods) UnsetIsArchived() ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.IsArchived = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m conversationParticipantMods) RandomIsArchived(f *faker.Faker) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.IsArchived = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m conversationParticipantMods) LastReadAt(val null.Val[time.Time]) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.LastReadAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m conversationParticipantMods) LastReadAtFunc(f func() null.Val[time.Time]) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.LastReadAt = f
	})
}

// Clear any values for the column
func (m conversationParticipantMods) UnsetLastReadAt() ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.LastReadAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m conversationParticipantMods) RandomLastReadAt(f *faker.Faker) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.LastReadAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m conversationParticipantMods) RandomLastReadAtNotNull(f *faker.Faker) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.LastReadAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m conversationParticipantMods) JoinedAt(val time.Time) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.JoinedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m conversationParticipantMods) JoinedAtFunc(f func() time.Time) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.JoinedAt = f
	})
}

// Clear any values for the column
func (m conversationParticipantMods) UnsetJoinedAt() ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.JoinedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m conversationParticipantMods) RandomJoinedAt(f *faker.Faker) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.JoinedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m conversationParticipantMods) LeftAt(val null.Val[time.Time]) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.LeftAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m conversationParticipantMods) LeftAtFunc(f func() null.Val[time.Time]) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.LeftAt = f
	})
}

// Clear any values for the column
func (m conversationParticipantMods) UnsetLeftAt() ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.LeftAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m conversationParticipantMods) RandomLeftAt(f *faker.Faker) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.LeftAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m conversationParticipantMods) RandomLeftAtNotNull(f *faker.Faker) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.LeftAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m conversationParticipantMods) UpdatedAt(val time.Time) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m conversationParticipantMods) UpdatedAtFunc(f func() time.Time) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m conversationParticipantMods) UnsetUpdatedAt() ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m conversationParticipantMods) RandomUpdatedAt(f *faker.Faker) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(_ context.Context, o *ConversationParticipantTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m conversationParticipantMods) WithParentsCascading() ConversationParticipantMod {
	return ConversationParticipantModFunc(func(ctx context.Context, o *ConversationParticipantTemplate) {
		if isDone, _ := conversationParticipantWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = conversationParticipantWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewConversationWithContext(ctx, ConversationMods.WithParentsCascading())
			m.WithConversation(related).Apply(ctx, o)
		}
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m conversationParticipantMods) WithConversation(rel *ConversationTemplate) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(ctx context.Context, o *ConversationParticipantTemplate) {
		o.r.Conversation = &conversationParticipantRConversationR{
			o: rel,
		}
	})
}

func (m conversationParticipantMods) WithNewConversation(mods ...ConversationMod) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(ctx context.Context, o *ConversationParticipantTemplate) {
		related := o.f.NewConversationWithContext(ctx, mods...)

		m.WithConversation(related).Apply(ctx, o)
	})
}

func (m conversationParticipantMods) WithExistingConversation(em *models.Conversation) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(ctx context.Context, o *ConversationParticipantTemplate) {
		o.r.Conversation = &conversationParticipantRConversationR{
			o: o.f.FromExistingConversation(em),
		}
	})
}

func (m conversationParticipantMods) WithoutConversation() ConversationParticipantMod {
	return ConversationParticipantModFunc(func(ctx context.Context, o *ConversationParticipantTemplate) {
		o.r.Conversation = nil
	})
}

func (m conversationParticipantMods) WithUser(rel *UserTemplate) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(ctx context.Context, o *ConversationParticipantTemplate) {
		o.r.User = &conversationParticipantRUserR{
			o: rel,
		}
	})
}

func (m conversationParticipantMods) WithNewUser(mods ...UserMod) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(ctx context.Context, o *ConversationParticipantTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m conversationParticipantMods) WithExistingUser(em *models.User) ConversationParticipantMod {
	return ConversationParticipantModFunc(func(ctx context.Context, o *ConversationParticipantTemplate) {
		o.r.User = &conversationParticipantRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m conversationParticipantMods) WithoutUser() ConversationParticipantMod {
	return ConversationParticipantModFunc(func(ctx context.Context, o *ConversationParticipantTemplate) {
		o.r.User = nil
	})
}
