// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	models "github.com/danielng/kin-core-svc/models"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type PlaceMod interface {
	Apply(context.Context, *PlaceTemplate)
}

type PlaceModFunc func(context.Context, *PlaceTemplate)

func (f PlaceModFunc) Apply(ctx context.Context, n *PlaceTemplate) {
	f(ctx, n)
}

type PlaceModSlice []PlaceMod

func (mods PlaceModSlice) Apply(ctx context.Context, n *PlaceTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// PlaceTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type PlaceTemplate struct {
	ID        func() uuid.UUID
	UserID    func() uuid.UUID
	Name      func() string
	Type      func() string
	Latitude  func() float64
	Longitude func() float64
	Radius    func() float64
	Address   func() null.Val[string]
	Icon      func() null.Val[string]
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	r placeR
	f *Factory

	alreadyPersisted bool
}

type placeR struct {
	CheckIns []*placeRCheckInsR
	User     *placeRUserR
}

type placeRCheckInsR struct {
	number int
	o      *CheckInTemplate
}
type placeRUserR struct {
	o *UserTemplate
}

// Apply mods to the PlaceTemplate
func (o *PlaceTemplate) Apply(ctx context.Context, mods ...PlaceMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Place
// according to the relationships in the template. Nothing is inserted into the db
func (t PlaceTemplate) setModelRels(o *models.Place) {
	if t.r.CheckIns != nil {
		rel := models.CheckInSlice{}
		for _, r := range t.r.CheckIns {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.PlaceID = o.ID // h2
				rel.R.Place = o
			}
			rel = append(rel, related...)
		}
		o.R.CheckIns = rel
	}

	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.Places = append(rel.R.Places, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.PlaceSetter
// this does nothing with the relationship templates
func (o PlaceTemplate) BuildSetter() *models.PlaceSetter {
	m := &models.PlaceSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.Type != nil {
		val := o.Type()
		m.Type = omit.From(val)
	}
	if o.Latitude != nil {
		val := o.Latitude()
		m.Latitude = omit.From(val)
	}
	if o.Longitude != nil {
		val := o.Longitude()
		m.Longitude = omit.From(val)
	}
	if o.Radius != nil {
		val := o.Radius()
		m.Radius = omit.From(val)
	}
	if o.Address != nil {
		val := o.Address()
		m.Address = omitnull.FromNull(val)
	}
	if o.Icon != nil {
		val := o.Icon()
		m.Icon = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.PlaceSetter
// this does nothing with the relationship templates
func (o PlaceTemplate) BuildManySetter(number int) []*models.PlaceSetter {
	m := make([]*models.PlaceSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Place
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use PlaceTemplate.Create
func (o PlaceTemplate) Build() *models.Place {
	m := &models.Place{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Type != nil {
		m.Type = o.Type()
	}
	if o.Latitude != nil {
		m.Latitude = o.Latitude()
	}
	if o.Longitude != nil {
		m.Longitude = o.Longitude()
	}
	if o.Radius != nil {
		m.Radius = o.Radius()
	}
	if o.Address != nil {
		m.Address = o.Address()
	}
	if o.Icon != nil {
		m.Icon = o.Icon()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.PlaceSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use PlaceTemplate.CreateMany
func (o PlaceTemplate) BuildMany(number int) models.PlaceSlice {
	m := make(models.PlaceSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatablePlace(m *models.PlaceSetter) {
	if !(m.ID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.UserID = omit.From(val)
	}
	if !(m.Name.IsValue()) {
		val := random_string(nil, "100")
		m.Name = omit.From(val)
	}
	if !(m.Type.IsValue()) {
		val := random_string(nil, "20")
		m.Type = omit.From(val)
	}
	if !(m.Latitude.IsValue()) {
		val := random_float64(nil)
		m.Latitude = omit.From(val)
	}
	if !(m.Longitude.IsValue()) {
		val := random_float64(nil)
		m.Longitude = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Place
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *PlaceTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Place) error {
	var err error

	isCheckInsDone, _ := placeRelCheckInsCtx.Value(ctx)
	if !isCheckInsDone && o.r.CheckIns != nil {
		ctx = placeRelCheckInsCtx.WithValue(ctx, true)
		for _, r := range o.r.CheckIns {
			if r.o.alreadyPersisted {
				m.R.CheckIns = append(m.R.CheckIns, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachCheckIns(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a place and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *PlaceTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Place, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatablePlace(opt)

	if o.r.User == nil {
		PlaceMods.WithNewUser().Apply(ctx, o)
	}

	var rel1 *models.User

	if o.r.User.o.alreadyPersisted {
		rel1 = o.r.User.o.Build()
	} else {
		rel1, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel1.ID)

	m, err := models.Places.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a place and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *PlaceTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Place {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a place and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *PlaceTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Place {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple places and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o PlaceTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.PlaceSlice, error) {
	var err error
	m := make(models.PlaceSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple places and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o PlaceTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.PlaceSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple places and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o PlaceTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.PlaceSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Place has methods that act as mods for the PlaceTemplate
var PlaceMods placeMods

type placeMods struct{}

func (m placeMods) RandomizeAllColumns(f *faker.Faker) PlaceMod {
	return PlaceModSlice{
		PlaceMods.RandomID(f),
		PlaceMods.RandomUserID(f),
		PlaceMods.RandomName(f),
		PlaceMods.RandomType(f),
		PlaceMods.RandomLatitude(f),
		PlaceMods.RandomLongitude(f),
		PlaceMods.RandomRadius(f),
		PlaceMods.RandomAddress(f),
		PlaceMods.RandomIcon(f),
		PlaceMods.RandomCreatedAt(f),
		PlaceMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m placeMods) ID(val uuid.UUID) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m placeMods) IDFunc(f func() uuid.UUID) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m placeMods) UnsetID() PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m placeMods) RandomID(f *faker.Faker) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m placeMods) UserID(val uuid.UUID) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.UserID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m placeMods) UserIDFunc(f func() uuid.UUID) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m placeMods) UnsetUserID() PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m placeMods) RandomUserID(f *faker.Faker) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.UserID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m placeMods) Name(val string) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m placeMods) NameFunc(f func() string) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m placeMods) UnsetName() PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m placeMods) RandomName(f *faker.Faker) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Name = func() string {
			return random_string(f, "100")
		}
	})
}

// Set the model columns to this value
func (m placeMods) Type(val string) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Type = func() string { return val }
	})
}

// Set the Column from the function
func (m placeMods) TypeFunc(f func() string) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Type = f
	})
}

// Clear any values for the column
func (m placeMods) UnsetType() PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Type = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m placeMods) RandomType(f *faker.Faker) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Type = func() string {
			return random_string(f, "20")
		}
	})
}

// Set the model columns to this value
func (m placeMods) Latitude(val float64) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Latitude = func() float64 { return val }
	})
}

// Set the Column from the function
func (m placeMods) LatitudeFunc(f func() float64) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Latitude = f
	})
}

// Clear any values for the column
func (m placeMods) UnsetLatitude() PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Latitude = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m placeMods) RandomLatitude(f *faker.Faker) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Latitude = func() float64 {
			return random_float64(f)
		}
	})
}

// Set the model columns to this value
func (m placeMods) Longitude(val float64) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Longitude = func() float64 { return val }
	})
}

// Set the Column from the function
func (m placeMods) LongitudeFunc(f func() float64) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Longitude = f
	})
}

// Clear any values for the column
func (m placeMods) UnsetLongitude() PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Longitude = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m placeMods) RandomLongitude(f *faker.Faker) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Longitude = func() float64 {
			return random_float64(f)
		}
	})
}

// Set the model columns to this value
func (m placeMods) Radius(val float64) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Radius = func() float64 { return val }
	})
}

// Set the Column from the function
func (m placeMods) RadiusFunc(f func() float64) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Radius = f
	})
}

// Clear any values for the column
func (m placeMods) UnsetRadius() PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Radius = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m placeMods) RandomRadius(f *faker.Faker) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Radius = func() float64 {
			return random_float64(f)
		}
	})
}

// Set the model columns to this value
func (m placeMods) Address(val null.Val[string]) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Address = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m placeMods) AddressFunc(f func() null.Val[string]) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Address = f
	})
}

// Clear any values for the column
func (m placeMods) UnsetAddress() PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Address = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m placeMods) RandomAddress(f *faker.Faker) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Address = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m placeMods) RandomAddressNotNull(f *faker.Faker) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Address = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m placeMods) Icon(val null.Val[string]) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Icon = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m placeMods) IconFunc(f func() null.Val[string]) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Icon = f
	})
}

// Clear any values for the column
func (m placeMods) UnsetIcon() PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Icon = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m placeMods) RandomIcon(f *faker.Faker) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Icon = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "50")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m placeMods) RandomIconNotNull(f *faker.Faker) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.Icon = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "50")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m placeMods) CreatedAt(val time.Time) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m placeMods) CreatedAtFunc(f func() time.Time) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m placeMods) UnsetCreatedAt() PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m placeMods) RandomCreatedAt(f *faker.Faker) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m placeMods) UpdatedAt(val time.Time) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m placeMods) UpdatedAtFunc(f func() time.Time) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m placeMods) UnsetUpdatedAt() PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m placeMods) RandomUpdatedAt(f *faker.Faker) PlaceMod {
	return PlaceModFunc(func(_ context.Context, o *PlaceTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m placeMods) WithParentsCascading() PlaceMod {
	return PlaceModFunc(func(ctx context.Context, o *PlaceTemplate) {
		if isDone, _ := placeWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = placeWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m placeMods) WithUser(rel *UserTemplate) PlaceMod {
	return PlaceModFunc(func(ctx context.Context, o *PlaceTemplate) {
		o.r.User = &placeRUserR{
			o: rel,
		}
	})
}

func (m placeMods) WithNewUser(mods ...UserMod) PlaceMod {
	return PlaceModFunc(func(ctx context.Context, o *PlaceTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m placeMods) WithExistingUser(em *models.User) PlaceMod {
	return PlaceModFunc(func(ctx context.Context, o *PlaceTemplate) {
		o.r.User = &placeRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m placeMods) WithoutUser() PlaceMod {
	return PlaceModFunc(func(ctx context.Context, o *PlaceTemplate) {
		o.r.User = nil
	})
}

func (m placeMods) WithCheckIns(number int, related *CheckInTemplate) PlaceMod {
	return PlaceModFunc(func(ctx context.Context, o *PlaceTemplate) {
		o.r.CheckIns = []*placeRCheckInsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m placeMods) WithNewCheckIns(number int, mods ...CheckInMod) PlaceMod {
	return PlaceModFunc(func(ctx context.Context, o *PlaceTemplate) {
		related := o.f.NewCheckInWithContext(ctx, mods...)
		m.WithCheckIns(number, related).Apply(ctx, o)
	})
}

func (m placeMods) AddCheckIns(number int, related *CheckInTemplate) PlaceMod {
	return PlaceModFunc(func(ctx context.Context, o *PlaceTemplate) {
		o.r.CheckIns = append(o.r.CheckIns, &placeRCheckInsR{
			number: number,
			o:      related,
		})
	})
}

func (m placeMods) AddNewCheckIns(number int, mods ...CheckInMod) PlaceMod {
	return PlaceModFunc(func(ctx context.Context, o *PlaceTemplate) {
		related := o.f.NewCheckInWithContext(ctx, mods...)
		m.AddCheckIns(number, related).Apply(ctx, o)
	})
}

func (m placeMods) AddExistingCheckIns(existingModels ...*models.CheckIn) PlaceMod {
	return PlaceModFunc(func(ctx context.Context, o *PlaceTemplate) {
		for _, em := range existingModels {
			o.r.CheckIns = append(o.r.CheckIns, &placeRCheckInsR{
				o: o.f.FromExistingCheckIn(em),
			})
		}
	})
}

func (m placeMods) WithoutCheckIns() PlaceMod {
	return PlaceModFunc(func(ctx context.Context, o *PlaceTemplate) {
		o.r.CheckIns = nil
	})
}
