// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var CircleInvitations = Table[
	circleInvitationColumns,
	circleInvitationIndexes,
	circleInvitationForeignKeys,
	circleInvitationUniques,
	circleInvitationChecks,
]{
	Schema: "",
	Name:   "circle_invitations",
	Columns: circleInvitationColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CircleID: column{
			Name:      "circle_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InviterID: column{
			Name:      "inviter_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InviteeID: column{
			Name:      "invitee_id",
			DBType:    "uuid",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Type: column{
			Name:      "type",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Code: column{
			Name:      "code",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "character varying",
			Default:   "'pending'::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		MaxUses: column{
			Name:      "max_uses",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UseCount: column{
			Name:      "use_count",
			DBType:    "integer",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ExpiresAt: column{
			Name:      "expires_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: circleInvitationIndexes{
		CircleInvitationsPkey: index{
			Type: "btree",
			Name: "circle_invitations_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		CircleInvitationsCodeKey: index{
			Type: "btree",
			Name: "circle_invitations_code_key",
			Columns: []indexColumn{
				{
					Name:         "code",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxCircleInvitationsCode: index{
			Type: "btree",
			Name: "idx_circle_invitations_code",
			Columns: []indexColumn{
				{
					Name:         "code",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxCircleInvitationsInvitee: index{
			Type: "btree",
			Name: "idx_circle_invitations_invitee",
			Columns: []indexColumn{
				{
					Name:         "invitee_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "circle_invitations_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: circleInvitationForeignKeys{
		CircleInvitationsFKCircleInvitationsCircleID: foreignKey{
			constraint: constraint{
				Name:    "circle_invitations.fk_circle_invitations_circle_id",
				Columns: []string{"circle_id"},
				Comment: "",
			},
			ForeignTable:   "circles",
			ForeignColumns: []string{"id"},
		},
		CircleInvitationsFKCircleInvitationsInviteeID: foreignKey{
			constraint: constraint{
				Name:    "circle_invitations.fk_circle_invitations_invitee_id",
				Columns: []string{"invitee_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
		CircleInvitationsFKCircleInvitationsInviterID: foreignKey{
			constraint: constraint{
				Name:    "circle_invitations.fk_circle_invitations_inviter_id",
				Columns: []string{"inviter_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: circleInvitationUniques{
		CircleInvitationsCodeKey: constraint{
			Name:    "circle_invitations_code_key",
			Columns: []string{"code"},
			Comment: "",
		},
	},

	Comment: "",
}

type circleInvitationColumns struct {
	ID        column
	CircleID  column
	InviterID column
	InviteeID column
	Type      column
	Code      column
	Status    column
	MaxUses   column
	UseCount  column
	ExpiresAt column
	CreatedAt column
	UpdatedAt column
}

func (c circleInvitationColumns) AsSlice() []column {
	return []column{
		c.ID, c.CircleID, c.InviterID, c.InviteeID, c.Type, c.Code, c.Status, c.MaxUses, c.UseCount, c.ExpiresAt, c.CreatedAt, c.UpdatedAt,
	}
}

type circleInvitationIndexes struct {
	CircleInvitationsPkey       index
	CircleInvitationsCodeKey    index
	IdxCircleInvitationsCode    index
	IdxCircleInvitationsInvitee index
}

func (i circleInvitationIndexes) AsSlice() []index {
	return []index{
		i.CircleInvitationsPkey, i.CircleInvitationsCodeKey, i.IdxCircleInvitationsCode, i.IdxCircleInvitationsInvitee,
	}
}

type circleInvitationForeignKeys struct {
	CircleInvitationsFKCircleInvitationsCircleID  foreignKey
	CircleInvitationsFKCircleInvitationsInviteeID foreignKey
	CircleInvitationsFKCircleInvitationsInviterID foreignKey
}

func (f circleInvitationForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.CircleInvitationsFKCircleInvitationsCircleID, f.CircleInvitationsFKCircleInvitationsInviteeID, f.CircleInvitationsFKCircleInvitationsInviterID,
	}
}

type circleInvitationUniques struct {
	CircleInvitationsCodeKey constraint
}

func (u circleInvitationUniques) AsSlice() []constraint {
	return []constraint{
		u.CircleInvitationsCodeKey,
	}
}

type circleInvitationChecks struct{}

func (c circleInvitationChecks) AsSlice() []check {
	return []check{}
}
