// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Media = Table[
	mediumColumns,
	mediumIndexes,
	mediumForeignKeys,
	mediumUniques,
	mediumChecks,
]{
	Schema: "",
	Name:   "media",
	Columns: mediumColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Type: column{
			Name:      "type",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		FileName: column{
			Name:      "file_name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		FileSize: column{
			Name:      "file_size",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		MimeType: column{
			Name:      "mime_type",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StorageKey: column{
			Name:      "storage_key",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		URL: column{
			Name:      "url",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ThumbnailKey: column{
			Name:      "thumbnail_key",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ThumbnailURL: column{
			Name:      "thumbnail_url",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Width: column{
			Name:      "width",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Height: column{
			Name:      "height",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Duration: column{
			Name:      "duration",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: mediumIndexes{
		MediaPkey: index{
			Type: "btree",
			Name: "media_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxMediaStorageKey: index{
			Type: "btree",
			Name: "idx_media_storage_key",
			Columns: []indexColumn{
				{
					Name:         "storage_key",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxMediaUser: index{
			Type: "btree",
			Name: "idx_media_user",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "media_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: mediumForeignKeys{
		MediaFKMediaUserID: foreignKey{
			constraint: constraint{
				Name:    "media.fk_media_user_id",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type mediumColumns struct {
	ID           column
	UserID       column
	Type         column
	FileName     column
	FileSize     column
	MimeType     column
	StorageKey   column
	URL          column
	ThumbnailKey column
	ThumbnailURL column
	Width        column
	Height       column
	Duration     column
	CreatedAt    column
}

func (c mediumColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.Type, c.FileName, c.FileSize, c.MimeType, c.StorageKey, c.URL, c.ThumbnailKey, c.ThumbnailURL, c.Width, c.Height, c.Duration, c.CreatedAt,
	}
}

type mediumIndexes struct {
	MediaPkey          index
	IdxMediaStorageKey index
	IdxMediaUser       index
}

func (i mediumIndexes) AsSlice() []index {
	return []index{
		i.MediaPkey, i.IdxMediaStorageKey, i.IdxMediaUser,
	}
}

type mediumForeignKeys struct {
	MediaFKMediaUserID foreignKey
}

func (f mediumForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.MediaFKMediaUserID,
	}
}

type mediumUniques struct{}

func (u mediumUniques) AsSlice() []constraint {
	return []constraint{}
}

type mediumChecks struct{}

func (c mediumChecks) AsSlice() []check {
	return []check{}
}
