// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var LocationHistoryErrors = &locationHistoryErrors{
	ErrUniqueLocationHistoryPkey: &UniqueConstraintError{
		schema:  "",
		table:   "location_history",
		columns: []string{"id"},
		s:       "location_history_pkey",
	},
}

type locationHistoryErrors struct {
	ErrUniqueLocationHistoryPkey *UniqueConstraintError
}
