// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var UserErrors = &userErrors{
	ErrUniqueUsersPkey: &UniqueConstraintError{
		schema:  "",
		table:   "users",
		columns: []string{"id"},
		s:       "users_pkey",
	},

	ErrUniqueUsersAuth0SubKey: &UniqueConstraintError{
		schema:  "",
		table:   "users",
		columns: []string{"auth0_sub"},
		s:       "users_auth0_sub_key",
	},
}

type userErrors struct {
	ErrUniqueUsersPkey *UniqueConstraintError

	ErrUniqueUsersAuth0SubKey *UniqueConstraintError
}
