// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// AvailabilityAutoRule is an object representing the database table.
type AvailabilityAutoRule struct {
	ID           uuid.UUID                   `db:"id,pk" `
	UserID       uuid.UUID                   `db:"user_id" `
	Name         string                      `db:"name" `
	Condition    types.JSON[json.RawMessage] `db:"condition" `
	TargetStatus string                      `db:"target_status" `
	Priority     int32                       `db:"priority" `
	IsActive     bool                        `db:"is_active" `
	CreatedAt    time.Time                   `db:"created_at" `
	UpdatedAt    time.Time                   `db:"updated_at" `

	R availabilityAutoRuleR `db:"-" `
}

// AvailabilityAutoRuleSlice is an alias for a slice of pointers to AvailabilityAutoRule.
// This should almost always be used instead of []*AvailabilityAutoRule.
type AvailabilityAutoRuleSlice []*AvailabilityAutoRule

// AvailabilityAutoRules contains methods to work with the availability_auto_rules table
var AvailabilityAutoRules = psql.NewTablex[*AvailabilityAutoRule, AvailabilityAutoRuleSlice, *AvailabilityAutoRuleSetter]("", "availability_auto_rules", buildAvailabilityAutoRuleColumns("availability_auto_rules"))

// AvailabilityAutoRulesQuery is a query on the availability_auto_rules table
type AvailabilityAutoRulesQuery = *psql.ViewQuery[*AvailabilityAutoRule, AvailabilityAutoRuleSlice]

// availabilityAutoRuleR is where relationships are stored.
type availabilityAutoRuleR struct {
	User *User // availability_auto_rules.fk_availability_auto_rules_user_id
}

func buildAvailabilityAutoRuleColumns(alias string) availabilityAutoRuleColumns {
	return availabilityAutoRuleColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "name", "condition", "target_status", "priority", "is_active", "created_at", "updated_at",
		).WithParent("availability_auto_rules"),
		tableAlias:   alias,
		ID:           psql.Quote(alias, "id"),
		UserID:       psql.Quote(alias, "user_id"),
		Name:         psql.Quote(alias, "name"),
		Condition:    psql.Quote(alias, "condition"),
		TargetStatus: psql.Quote(alias, "target_status"),
		Priority:     psql.Quote(alias, "priority"),
		IsActive:     psql.Quote(alias, "is_active"),
		CreatedAt:    psql.Quote(alias, "created_at"),
		UpdatedAt:    psql.Quote(alias, "updated_at"),
	}
}

type availabilityAutoRuleColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	ID           psql.Expression
	UserID       psql.Expression
	Name         psql.Expression
	Condition    psql.Expression
	TargetStatus psql.Expression
	Priority     psql.Expression
	IsActive     psql.Expression
	CreatedAt    psql.Expression
	UpdatedAt    psql.Expression
}

func (c availabilityAutoRuleColumns) Alias() string {
	return c.tableAlias
}

func (availabilityAutoRuleColumns) AliasedAs(alias string) availabilityAutoRuleColumns {
	return buildAvailabilityAutoRuleColumns(alias)
}

// AvailabilityAutoRuleSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type AvailabilityAutoRuleSetter struct {
	ID           omit.Val[uuid.UUID]                   `db:"id,pk" `
	UserID       omit.Val[uuid.UUID]                   `db:"user_id" `
	Name         omit.Val[string]                      `db:"name" `
	Condition    omit.Val[types.JSON[json.RawMessage]] `db:"condition" `
	TargetStatus omit.Val[string]                      `db:"target_status" `
	Priority     omit.Val[int32]                       `db:"priority" `
	IsActive     omit.Val[bool]                        `db:"is_active" `
	CreatedAt    omit.Val[time.Time]                   `db:"created_at" `
	UpdatedAt    omit.Val[time.Time]                   `db:"updated_at" `
}

func (s AvailabilityAutoRuleSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Condition.IsValue() {
		vals = append(vals, "condition")
	}
	if s.TargetStatus.IsValue() {
		vals = append(vals, "target_status")
	}
	if s.Priority.IsValue() {
		vals = append(vals, "priority")
	}
	if s.IsActive.IsValue() {
		vals = append(vals, "is_active")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s AvailabilityAutoRuleSetter) Overwrite(t *AvailabilityAutoRule) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Condition.IsValue() {
		t.Condition = s.Condition.MustGet()
	}
	if s.TargetStatus.IsValue() {
		t.TargetStatus = s.TargetStatus.MustGet()
	}
	if s.Priority.IsValue() {
		t.Priority = s.Priority.MustGet()
	}
	if s.IsActive.IsValue() {
		t.IsActive = s.IsActive.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *AvailabilityAutoRuleSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return AvailabilityAutoRules.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 9)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[2] = psql.Arg(s.Name.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Condition.IsValue() {
			vals[3] = psql.Arg(s.Condition.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.TargetStatus.IsValue() {
			vals[4] = psql.Arg(s.TargetStatus.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Priority.IsValue() {
			vals[5] = psql.Arg(s.Priority.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.IsActive.IsValue() {
			vals[6] = psql.Arg(s.IsActive.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[7] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[8] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s AvailabilityAutoRuleSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s AvailabilityAutoRuleSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Condition.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "condition")...),
			psql.Arg(s.Condition),
		}})
	}

	if s.TargetStatus.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "target_status")...),
			psql.Arg(s.TargetStatus),
		}})
	}

	if s.Priority.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "priority")...),
			psql.Arg(s.Priority),
		}})
	}

	if s.IsActive.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_active")...),
			psql.Arg(s.IsActive),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindAvailabilityAutoRule retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindAvailabilityAutoRule(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*AvailabilityAutoRule, error) {
	if len(cols) == 0 {
		return AvailabilityAutoRules.Query(
			sm.Where(AvailabilityAutoRules.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return AvailabilityAutoRules.Query(
		sm.Where(AvailabilityAutoRules.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(AvailabilityAutoRules.Columns.Only(cols...)),
	).One(ctx, exec)
}

// AvailabilityAutoRuleExists checks the presence of a single record by primary key
func AvailabilityAutoRuleExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return AvailabilityAutoRules.Query(
		sm.Where(AvailabilityAutoRules.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after AvailabilityAutoRule is retrieved from the database
func (o *AvailabilityAutoRule) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = AvailabilityAutoRules.AfterSelectHooks.RunHooks(ctx, exec, AvailabilityAutoRuleSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = AvailabilityAutoRules.AfterInsertHooks.RunHooks(ctx, exec, AvailabilityAutoRuleSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = AvailabilityAutoRules.AfterUpdateHooks.RunHooks(ctx, exec, AvailabilityAutoRuleSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = AvailabilityAutoRules.AfterDeleteHooks.RunHooks(ctx, exec, AvailabilityAutoRuleSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the AvailabilityAutoRule
func (o *AvailabilityAutoRule) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *AvailabilityAutoRule) pkEQ() dialect.Expression {
	return psql.Quote("availability_auto_rules", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the AvailabilityAutoRule
func (o *AvailabilityAutoRule) Update(ctx context.Context, exec bob.Executor, s *AvailabilityAutoRuleSetter) error {
	v, err := AvailabilityAutoRules.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single AvailabilityAutoRule record with an executor
func (o *AvailabilityAutoRule) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := AvailabilityAutoRules.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the AvailabilityAutoRule using the executor
func (o *AvailabilityAutoRule) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := AvailabilityAutoRules.Query(
		sm.Where(AvailabilityAutoRules.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after AvailabilityAutoRuleSlice is retrieved from the database
func (o AvailabilityAutoRuleSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = AvailabilityAutoRules.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = AvailabilityAutoRules.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = AvailabilityAutoRules.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = AvailabilityAutoRules.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o AvailabilityAutoRuleSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("availability_auto_rules", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o AvailabilityAutoRuleSlice) copyMatchingRows(from ...*AvailabilityAutoRule) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o AvailabilityAutoRuleSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return AvailabilityAutoRules.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *AvailabilityAutoRule:
				o.copyMatchingRows(retrieved)
			case []*AvailabilityAutoRule:
				o.copyMatchingRows(retrieved...)
			case AvailabilityAutoRuleSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a AvailabilityAutoRule or a slice of AvailabilityAutoRule
				// then run the AfterUpdateHooks on the slice
				_, err = AvailabilityAutoRules.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o AvailabilityAutoRuleSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return AvailabilityAutoRules.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *AvailabilityAutoRule:
				o.copyMatchingRows(retrieved)
			case []*AvailabilityAutoRule:
				o.copyMatchingRows(retrieved...)
			case AvailabilityAutoRuleSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a AvailabilityAutoRule or a slice of AvailabilityAutoRule
				// then run the AfterDeleteHooks on the slice
				_, err = AvailabilityAutoRules.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o AvailabilityAutoRuleSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals AvailabilityAutoRuleSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := AvailabilityAutoRules.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o AvailabilityAutoRuleSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := AvailabilityAutoRules.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o AvailabilityAutoRuleSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := AvailabilityAutoRules.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *AvailabilityAutoRule) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os AvailabilityAutoRuleSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachAvailabilityAutoRuleUser0(ctx context.Context, exec bob.Executor, count int, availabilityAutoRule0 *AvailabilityAutoRule, user1 *User) (*AvailabilityAutoRule, error) {
	setter := &AvailabilityAutoRuleSetter{
		UserID: omit.From(user1.ID),
	}

	err := availabilityAutoRule0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachAvailabilityAutoRuleUser0: %w", err)
	}

	return availabilityAutoRule0, nil
}

func (availabilityAutoRule0 *AvailabilityAutoRule) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachAvailabilityAutoRuleUser0(ctx, exec, 1, availabilityAutoRule0, user1)
	if err != nil {
		return err
	}

	availabilityAutoRule0.R.User = user1

	user1.R.AvailabilityAutoRules = append(user1.R.AvailabilityAutoRules, availabilityAutoRule0)

	return nil
}

func (availabilityAutoRule0 *AvailabilityAutoRule) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachAvailabilityAutoRuleUser0(ctx, exec, 1, availabilityAutoRule0, user1)
	if err != nil {
		return err
	}

	availabilityAutoRule0.R.User = user1

	user1.R.AvailabilityAutoRules = append(user1.R.AvailabilityAutoRules, availabilityAutoRule0)

	return nil
}

type availabilityAutoRuleWhere[Q psql.Filterable] struct {
	ID           psql.WhereMod[Q, uuid.UUID]
	UserID       psql.WhereMod[Q, uuid.UUID]
	Name         psql.WhereMod[Q, string]
	Condition    psql.WhereMod[Q, types.JSON[json.RawMessage]]
	TargetStatus psql.WhereMod[Q, string]
	Priority     psql.WhereMod[Q, int32]
	IsActive     psql.WhereMod[Q, bool]
	CreatedAt    psql.WhereMod[Q, time.Time]
	UpdatedAt    psql.WhereMod[Q, time.Time]
}

func (availabilityAutoRuleWhere[Q]) AliasedAs(alias string) availabilityAutoRuleWhere[Q] {
	return buildAvailabilityAutoRuleWhere[Q](buildAvailabilityAutoRuleColumns(alias))
}

func buildAvailabilityAutoRuleWhere[Q psql.Filterable](cols availabilityAutoRuleColumns) availabilityAutoRuleWhere[Q] {
	return availabilityAutoRuleWhere[Q]{
		ID:           psql.Where[Q, uuid.UUID](cols.ID),
		UserID:       psql.Where[Q, uuid.UUID](cols.UserID),
		Name:         psql.Where[Q, string](cols.Name),
		Condition:    psql.Where[Q, types.JSON[json.RawMessage]](cols.Condition),
		TargetStatus: psql.Where[Q, string](cols.TargetStatus),
		Priority:     psql.Where[Q, int32](cols.Priority),
		IsActive:     psql.Where[Q, bool](cols.IsActive),
		CreatedAt:    psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:    psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *AvailabilityAutoRule) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("availabilityAutoRule cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.AvailabilityAutoRules = AvailabilityAutoRuleSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("availabilityAutoRule has no relationship %q", name)
	}
}

type availabilityAutoRulePreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildAvailabilityAutoRulePreloader() availabilityAutoRulePreloader {
	return availabilityAutoRulePreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        AvailabilityAutoRules,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type availabilityAutoRuleThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildAvailabilityAutoRuleThenLoader[Q orm.Loadable]() availabilityAutoRuleThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return availabilityAutoRuleThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the availabilityAutoRule's User into the .R struct
func (o *AvailabilityAutoRule) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.AvailabilityAutoRules = AvailabilityAutoRuleSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the availabilityAutoRule's User into the .R struct
func (os AvailabilityAutoRuleSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.AvailabilityAutoRules = append(rel.R.AvailabilityAutoRules, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type availabilityAutoRuleJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j availabilityAutoRuleJoins[Q]) aliasedAs(alias string) availabilityAutoRuleJoins[Q] {
	return buildAvailabilityAutoRuleJoins[Q](buildAvailabilityAutoRuleColumns(alias), j.typ)
}

func buildAvailabilityAutoRuleJoins[Q dialect.Joinable](cols availabilityAutoRuleColumns, typ string) availabilityAutoRuleJoins[Q] {
	return availabilityAutoRuleJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
