// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"

	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type AvailabilityAutoRule runs hooks after queries
var _ bob.HookableType = &AvailabilityAutoRule{}

// Make sure the type AvailabilityWindow runs hooks after queries
var _ bob.HookableType = &AvailabilityWindow{}

// Make sure the type CheckIn runs hooks after queries
var _ bob.HookableType = &CheckIn{}

// Make sure the type CircleInvitation runs hooks after queries
var _ bob.HookableType = &CircleInvitation{}

// Make sure the type CircleMember runs hooks after queries
var _ bob.HookableType = &CircleMember{}

// Make sure the type CircleSharingPreference runs hooks after queries
var _ bob.HookableType = &CircleSharingPreference{}

// Make sure the type Circle runs hooks after queries
var _ bob.HookableType = &Circle{}

// Make sure the type ContactRequest runs hooks after queries
var _ bob.HookableType = &ContactRequest{}

// Make sure the type Contact runs hooks after queries
var _ bob.HookableType = &Contact{}

// Make sure the type ConversationParticipant runs hooks after queries
var _ bob.HookableType = &ConversationParticipant{}

// Make sure the type Conversation runs hooks after queries
var _ bob.HookableType = &Conversation{}

// Make sure the type LocationHistory runs hooks after queries
var _ bob.HookableType = &LocationHistory{}

// Make sure the type Medium runs hooks after queries
var _ bob.HookableType = &Medium{}

// Make sure the type MessageDeletion runs hooks after queries
var _ bob.HookableType = &MessageDeletion{}

// Make sure the type MessageReaction runs hooks after queries
var _ bob.HookableType = &MessageReaction{}

// Make sure the type MessageReceipt runs hooks after queries
var _ bob.HookableType = &MessageReceipt{}

// Make sure the type Message runs hooks after queries
var _ bob.HookableType = &Message{}

// Make sure the type Place runs hooks after queries
var _ bob.HookableType = &Place{}

// Make sure the type UserAvailability runs hooks after queries
var _ bob.HookableType = &UserAvailability{}

// Make sure the type UserLocation runs hooks after queries
var _ bob.HookableType = &UserLocation{}

// Make sure the type UserPreference runs hooks after queries
var _ bob.HookableType = &UserPreference{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}

// Make sure the type uuid.UUID satisfies database/sql.Scanner
var _ sql.Scanner = (*uuid.UUID)(nil)

// Make sure the type uuid.UUID satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(uuid.UUID)

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql.Scanner
var _ sql.Scanner = (*types.JSON[json.RawMessage])(nil)

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(types.JSON[json.RawMessage])
