// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q psql.Filterable]() struct {
	AvailabilityAutoRules    availabilityAutoRuleWhere[Q]
	AvailabilityWindows      availabilityWindowWhere[Q]
	CheckIns                 checkInWhere[Q]
	CircleInvitations        circleInvitationWhere[Q]
	CircleMembers            circleMemberWhere[Q]
	CircleSharingPreferences circleSharingPreferenceWhere[Q]
	Circles                  circleWhere[Q]
	ContactRequests          contactRequestWhere[Q]
	Contacts                 contactWhere[Q]
	ConversationParticipants conversationParticipantWhere[Q]
	Conversations            conversationWhere[Q]
	LocationHistories        locationHistoryWhere[Q]
	Media                    mediumWhere[Q]
	MessageDeletions         messageDeletionWhere[Q]
	MessageReactions         messageReactionWhere[Q]
	MessageReceipts          messageReceiptWhere[Q]
	Messages                 messageWhere[Q]
	Places                   placeWhere[Q]
	UserAvailabilities       userAvailabilityWhere[Q]
	UserLocations            userLocationWhere[Q]
	UserPreferences          userPreferenceWhere[Q]
	Users                    userWhere[Q]
} {
	return struct {
		AvailabilityAutoRules    availabilityAutoRuleWhere[Q]
		AvailabilityWindows      availabilityWindowWhere[Q]
		CheckIns                 checkInWhere[Q]
		CircleInvitations        circleInvitationWhere[Q]
		CircleMembers            circleMemberWhere[Q]
		CircleSharingPreferences circleSharingPreferenceWhere[Q]
		Circles                  circleWhere[Q]
		ContactRequests          contactRequestWhere[Q]
		Contacts                 contactWhere[Q]
		ConversationParticipants conversationParticipantWhere[Q]
		Conversations            conversationWhere[Q]
		LocationHistories        locationHistoryWhere[Q]
		Media                    mediumWhere[Q]
		MessageDeletions         messageDeletionWhere[Q]
		MessageReactions         messageReactionWhere[Q]
		MessageReceipts          messageReceiptWhere[Q]
		Messages                 messageWhere[Q]
		Places                   placeWhere[Q]
		UserAvailabilities       userAvailabilityWhere[Q]
		UserLocations            userLocationWhere[Q]
		UserPreferences          userPreferenceWhere[Q]
		Users                    userWhere[Q]
	}{
		AvailabilityAutoRules:    buildAvailabilityAutoRuleWhere[Q](AvailabilityAutoRules.Columns),
		AvailabilityWindows:      buildAvailabilityWindowWhere[Q](AvailabilityWindows.Columns),
		CheckIns:                 buildCheckInWhere[Q](CheckIns.Columns),
		CircleInvitations:        buildCircleInvitationWhere[Q](CircleInvitations.Columns),
		CircleMembers:            buildCircleMemberWhere[Q](CircleMembers.Columns),
		CircleSharingPreferences: buildCircleSharingPreferenceWhere[Q](CircleSharingPreferences.Columns),
		Circles:                  buildCircleWhere[Q](Circles.Columns),
		ContactRequests:          buildContactRequestWhere[Q](ContactRequests.Columns),
		Contacts:                 buildContactWhere[Q](Contacts.Columns),
		ConversationParticipants: buildConversationParticipantWhere[Q](ConversationParticipants.Columns),
		Conversations:            buildConversationWhere[Q](Conversations.Columns),
		LocationHistories:        buildLocationHistoryWhere[Q](LocationHistories.Columns),
		Media:                    buildMediumWhere[Q](Media.Columns),
		MessageDeletions:         buildMessageDeletionWhere[Q](MessageDeletions.Columns),
		MessageReactions:         buildMessageReactionWhere[Q](MessageReactions.Columns),
		MessageReceipts:          buildMessageReceiptWhere[Q](MessageReceipts.Columns),
		Messages:                 buildMessageWhere[Q](Messages.Columns),
		Places:                   buildPlaceWhere[Q](Places.Columns),
		UserAvailabilities:       buildUserAvailabilityWhere[Q](UserAvailabilities.Columns),
		UserLocations:            buildUserLocationWhere[Q](UserLocations.Columns),
		UserPreferences:          buildUserPreferenceWhere[Q](UserPreferences.Columns),
		Users:                    buildUserWhere[Q](Users.Columns),
	}
}
