// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"hash/maphash"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectJoins = getJoins[*dialect.SelectQuery]()
	UpdateJoins = getJoins[*dialect.UpdateQuery]()
	DeleteJoins = getJoins[*dialect.DeleteQuery]()
)

type joinSet[Q interface{ aliasedAs(string) Q }] struct {
	InnerJoin Q
	LeftJoin  Q
	RightJoin Q
}

func (j joinSet[Q]) AliasedAs(alias string) joinSet[Q] {
	return joinSet[Q]{
		InnerJoin: j.InnerJoin.aliasedAs(alias),
		LeftJoin:  j.LeftJoin.aliasedAs(alias),
		RightJoin: j.RightJoin.aliasedAs(alias),
	}
}

type joins[Q dialect.Joinable] struct {
	AvailabilityAutoRules    joinSet[availabilityAutoRuleJoins[Q]]
	AvailabilityWindows      joinSet[availabilityWindowJoins[Q]]
	CheckIns                 joinSet[checkInJoins[Q]]
	CircleInvitations        joinSet[circleInvitationJoins[Q]]
	CircleMembers            joinSet[circleMemberJoins[Q]]
	CircleSharingPreferences joinSet[circleSharingPreferenceJoins[Q]]
	Circles                  joinSet[circleJoins[Q]]
	ContactRequests          joinSet[contactRequestJoins[Q]]
	Contacts                 joinSet[contactJoins[Q]]
	ConversationParticipants joinSet[conversationParticipantJoins[Q]]
	Conversations            joinSet[conversationJoins[Q]]
	LocationHistories        joinSet[locationHistoryJoins[Q]]
	Media                    joinSet[mediumJoins[Q]]
	MessageDeletions         joinSet[messageDeletionJoins[Q]]
	MessageReactions         joinSet[messageReactionJoins[Q]]
	MessageReceipts          joinSet[messageReceiptJoins[Q]]
	Messages                 joinSet[messageJoins[Q]]
	Places                   joinSet[placeJoins[Q]]
	UserAvailabilities       joinSet[userAvailabilityJoins[Q]]
	UserLocations            joinSet[userLocationJoins[Q]]
	UserPreferences          joinSet[userPreferenceJoins[Q]]
	Users                    joinSet[userJoins[Q]]
}

func buildJoinSet[Q interface{ aliasedAs(string) Q }, C any, F func(C, string) Q](c C, f F) joinSet[Q] {
	return joinSet[Q]{
		InnerJoin: f(c, clause.InnerJoin),
		LeftJoin:  f(c, clause.LeftJoin),
		RightJoin: f(c, clause.RightJoin),
	}
}

func getJoins[Q dialect.Joinable]() joins[Q] {
	return joins[Q]{
		AvailabilityAutoRules:    buildJoinSet[availabilityAutoRuleJoins[Q]](AvailabilityAutoRules.Columns, buildAvailabilityAutoRuleJoins),
		AvailabilityWindows:      buildJoinSet[availabilityWindowJoins[Q]](AvailabilityWindows.Columns, buildAvailabilityWindowJoins),
		CheckIns:                 buildJoinSet[checkInJoins[Q]](CheckIns.Columns, buildCheckInJoins),
		CircleInvitations:        buildJoinSet[circleInvitationJoins[Q]](CircleInvitations.Columns, buildCircleInvitationJoins),
		CircleMembers:            buildJoinSet[circleMemberJoins[Q]](CircleMembers.Columns, buildCircleMemberJoins),
		CircleSharingPreferences: buildJoinSet[circleSharingPreferenceJoins[Q]](CircleSharingPreferences.Columns, buildCircleSharingPreferenceJoins),
		Circles:                  buildJoinSet[circleJoins[Q]](Circles.Columns, buildCircleJoins),
		ContactRequests:          buildJoinSet[contactRequestJoins[Q]](ContactRequests.Columns, buildContactRequestJoins),
		Contacts:                 buildJoinSet[contactJoins[Q]](Contacts.Columns, buildContactJoins),
		ConversationParticipants: buildJoinSet[conversationParticipantJoins[Q]](ConversationParticipants.Columns, buildConversationParticipantJoins),
		Conversations:            buildJoinSet[conversationJoins[Q]](Conversations.Columns, buildConversationJoins),
		LocationHistories:        buildJoinSet[locationHistoryJoins[Q]](LocationHistories.Columns, buildLocationHistoryJoins),
		Media:                    buildJoinSet[mediumJoins[Q]](Media.Columns, buildMediumJoins),
		MessageDeletions:         buildJoinSet[messageDeletionJoins[Q]](MessageDeletions.Columns, buildMessageDeletionJoins),
		MessageReactions:         buildJoinSet[messageReactionJoins[Q]](MessageReactions.Columns, buildMessageReactionJoins),
		MessageReceipts:          buildJoinSet[messageReceiptJoins[Q]](MessageReceipts.Columns, buildMessageReceiptJoins),
		Messages:                 buildJoinSet[messageJoins[Q]](Messages.Columns, buildMessageJoins),
		Places:                   buildJoinSet[placeJoins[Q]](Places.Columns, buildPlaceJoins),
		UserAvailabilities:       buildJoinSet[userAvailabilityJoins[Q]](UserAvailabilities.Columns, buildUserAvailabilityJoins),
		UserLocations:            buildJoinSet[userLocationJoins[Q]](UserLocations.Columns, buildUserLocationJoins),
		UserPreferences:          buildJoinSet[userPreferenceJoins[Q]](UserPreferences.Columns, buildUserPreferenceJoins),
		Users:                    buildJoinSet[userJoins[Q]](Users.Columns, buildUserJoins),
	}
}

type modAs[Q any, C interface{ AliasedAs(string) C }] struct {
	c C
	f func(C) bob.Mod[Q]
}

func (m modAs[Q, C]) Apply(q Q) {
	m.f(m.c).Apply(q)
}

func (m modAs[Q, C]) AliasedAs(alias string) bob.Mod[Q] {
	m.c = m.c.AliasedAs(alias)
	return m
}

func randInt() int64 {
	out := int64(new(maphash.Hash).Sum64())

	if out < 0 {
		return -out % 10000
	}

	return out % 10000
}
