// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// CircleMember is an object representing the database table.
type CircleMember struct {
	ID        uuid.UUID        `db:"id,pk" `
	CircleID  uuid.UUID        `db:"circle_id" `
	UserID    uuid.UUID        `db:"user_id" `
	Role      string           `db:"role" `
	Nickname  null.Val[string] `db:"nickname" `
	JoinedAt  time.Time        `db:"joined_at" `
	UpdatedAt time.Time        `db:"updated_at" `

	R circleMemberR `db:"-" `
}

// CircleMemberSlice is an alias for a slice of pointers to CircleMember.
// This should almost always be used instead of []*CircleMember.
type CircleMemberSlice []*CircleMember

// CircleMembers contains methods to work with the circle_members table
var CircleMembers = psql.NewTablex[*CircleMember, CircleMemberSlice, *CircleMemberSetter]("", "circle_members", buildCircleMemberColumns("circle_members"))

// CircleMembersQuery is a query on the circle_members table
type CircleMembersQuery = *psql.ViewQuery[*CircleMember, CircleMemberSlice]

// circleMemberR is where relationships are stored.
type circleMemberR struct {
	Circle *Circle // circle_members.fk_circle_members_circle_id
	User   *User   // circle_members.fk_circle_members_user_id
}

func buildCircleMemberColumns(alias string) circleMemberColumns {
	return circleMemberColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "circle_id", "user_id", "role", "nickname", "joined_at", "updated_at",
		).WithParent("circle_members"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		CircleID:   psql.Quote(alias, "circle_id"),
		UserID:     psql.Quote(alias, "user_id"),
		Role:       psql.Quote(alias, "role"),
		Nickname:   psql.Quote(alias, "nickname"),
		JoinedAt:   psql.Quote(alias, "joined_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type circleMemberColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	CircleID   psql.Expression
	UserID     psql.Expression
	Role       psql.Expression
	Nickname   psql.Expression
	JoinedAt   psql.Expression
	UpdatedAt  psql.Expression
}

func (c circleMemberColumns) Alias() string {
	return c.tableAlias
}

func (circleMemberColumns) AliasedAs(alias string) circleMemberColumns {
	return buildCircleMemberColumns(alias)
}

// CircleMemberSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CircleMemberSetter struct {
	ID        omit.Val[uuid.UUID]  `db:"id,pk" `
	CircleID  omit.Val[uuid.UUID]  `db:"circle_id" `
	UserID    omit.Val[uuid.UUID]  `db:"user_id" `
	Role      omit.Val[string]     `db:"role" `
	Nickname  omitnull.Val[string] `db:"nickname" `
	JoinedAt  omit.Val[time.Time]  `db:"joined_at" `
	UpdatedAt omit.Val[time.Time]  `db:"updated_at" `
}

func (s CircleMemberSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.CircleID.IsValue() {
		vals = append(vals, "circle_id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Role.IsValue() {
		vals = append(vals, "role")
	}
	if !s.Nickname.IsUnset() {
		vals = append(vals, "nickname")
	}
	if s.JoinedAt.IsValue() {
		vals = append(vals, "joined_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s CircleMemberSetter) Overwrite(t *CircleMember) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.CircleID.IsValue() {
		t.CircleID = s.CircleID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Role.IsValue() {
		t.Role = s.Role.MustGet()
	}
	if !s.Nickname.IsUnset() {
		t.Nickname = s.Nickname.MustGetNull()
	}
	if s.JoinedAt.IsValue() {
		t.JoinedAt = s.JoinedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *CircleMemberSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return CircleMembers.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 7)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.CircleID.IsValue() {
			vals[1] = psql.Arg(s.CircleID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[2] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Role.IsValue() {
			vals[3] = psql.Arg(s.Role.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.Nickname.IsUnset() {
			vals[4] = psql.Arg(s.Nickname.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.JoinedAt.IsValue() {
			vals[5] = psql.Arg(s.JoinedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[6] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s CircleMemberSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s CircleMemberSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.CircleID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "circle_id")...),
			psql.Arg(s.CircleID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Role.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "role")...),
			psql.Arg(s.Role),
		}})
	}

	if !s.Nickname.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "nickname")...),
			psql.Arg(s.Nickname),
		}})
	}

	if s.JoinedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "joined_at")...),
			psql.Arg(s.JoinedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindCircleMember retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCircleMember(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*CircleMember, error) {
	if len(cols) == 0 {
		return CircleMembers.Query(
			sm.Where(CircleMembers.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return CircleMembers.Query(
		sm.Where(CircleMembers.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(CircleMembers.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CircleMemberExists checks the presence of a single record by primary key
func CircleMemberExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return CircleMembers.Query(
		sm.Where(CircleMembers.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after CircleMember is retrieved from the database
func (o *CircleMember) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CircleMembers.AfterSelectHooks.RunHooks(ctx, exec, CircleMemberSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = CircleMembers.AfterInsertHooks.RunHooks(ctx, exec, CircleMemberSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = CircleMembers.AfterUpdateHooks.RunHooks(ctx, exec, CircleMemberSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = CircleMembers.AfterDeleteHooks.RunHooks(ctx, exec, CircleMemberSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the CircleMember
func (o *CircleMember) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *CircleMember) pkEQ() dialect.Expression {
	return psql.Quote("circle_members", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the CircleMember
func (o *CircleMember) Update(ctx context.Context, exec bob.Executor, s *CircleMemberSetter) error {
	v, err := CircleMembers.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single CircleMember record with an executor
func (o *CircleMember) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := CircleMembers.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the CircleMember using the executor
func (o *CircleMember) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := CircleMembers.Query(
		sm.Where(CircleMembers.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after CircleMemberSlice is retrieved from the database
func (o CircleMemberSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CircleMembers.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = CircleMembers.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = CircleMembers.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = CircleMembers.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CircleMemberSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("circle_members", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CircleMemberSlice) copyMatchingRows(from ...*CircleMember) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CircleMemberSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return CircleMembers.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *CircleMember:
				o.copyMatchingRows(retrieved)
			case []*CircleMember:
				o.copyMatchingRows(retrieved...)
			case CircleMemberSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a CircleMember or a slice of CircleMember
				// then run the AfterUpdateHooks on the slice
				_, err = CircleMembers.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CircleMemberSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return CircleMembers.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *CircleMember:
				o.copyMatchingRows(retrieved)
			case []*CircleMember:
				o.copyMatchingRows(retrieved...)
			case CircleMemberSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a CircleMember or a slice of CircleMember
				// then run the AfterDeleteHooks on the slice
				_, err = CircleMembers.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o CircleMemberSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CircleMemberSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := CircleMembers.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o CircleMemberSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := CircleMembers.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CircleMemberSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := CircleMembers.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Circle starts a query for related objects on circles
func (o *CircleMember) Circle(mods ...bob.Mod[*dialect.SelectQuery]) CirclesQuery {
	return Circles.Query(append(mods,
		sm.Where(Circles.Columns.ID.EQ(psql.Arg(o.CircleID))),
	)...)
}

func (os CircleMemberSlice) Circle(mods ...bob.Mod[*dialect.SelectQuery]) CirclesQuery {
	pkCircleID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkCircleID = append(pkCircleID, o.CircleID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkCircleID), "uuid[]")),
	))

	return Circles.Query(append(mods,
		sm.Where(psql.Group(Circles.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on users
func (o *CircleMember) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os CircleMemberSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachCircleMemberCircle0(ctx context.Context, exec bob.Executor, count int, circleMember0 *CircleMember, circle1 *Circle) (*CircleMember, error) {
	setter := &CircleMemberSetter{
		CircleID: omit.From(circle1.ID),
	}

	err := circleMember0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCircleMemberCircle0: %w", err)
	}

	return circleMember0, nil
}

func (circleMember0 *CircleMember) InsertCircle(ctx context.Context, exec bob.Executor, related *CircleSetter) error {
	var err error

	circle1, err := Circles.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCircleMemberCircle0(ctx, exec, 1, circleMember0, circle1)
	if err != nil {
		return err
	}

	circleMember0.R.Circle = circle1

	circle1.R.CircleMembers = append(circle1.R.CircleMembers, circleMember0)

	return nil
}

func (circleMember0 *CircleMember) AttachCircle(ctx context.Context, exec bob.Executor, circle1 *Circle) error {
	var err error

	_, err = attachCircleMemberCircle0(ctx, exec, 1, circleMember0, circle1)
	if err != nil {
		return err
	}

	circleMember0.R.Circle = circle1

	circle1.R.CircleMembers = append(circle1.R.CircleMembers, circleMember0)

	return nil
}

func attachCircleMemberUser0(ctx context.Context, exec bob.Executor, count int, circleMember0 *CircleMember, user1 *User) (*CircleMember, error) {
	setter := &CircleMemberSetter{
		UserID: omit.From(user1.ID),
	}

	err := circleMember0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCircleMemberUser0: %w", err)
	}

	return circleMember0, nil
}

func (circleMember0 *CircleMember) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCircleMemberUser0(ctx, exec, 1, circleMember0, user1)
	if err != nil {
		return err
	}

	circleMember0.R.User = user1

	user1.R.CircleMembers = append(user1.R.CircleMembers, circleMember0)

	return nil
}

func (circleMember0 *CircleMember) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachCircleMemberUser0(ctx, exec, 1, circleMember0, user1)
	if err != nil {
		return err
	}

	circleMember0.R.User = user1

	user1.R.CircleMembers = append(user1.R.CircleMembers, circleMember0)

	return nil
}

type circleMemberWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, uuid.UUID]
	CircleID  psql.WhereMod[Q, uuid.UUID]
	UserID    psql.WhereMod[Q, uuid.UUID]
	Role      psql.WhereMod[Q, string]
	Nickname  psql.WhereNullMod[Q, string]
	JoinedAt  psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (circleMemberWhere[Q]) AliasedAs(alias string) circleMemberWhere[Q] {
	return buildCircleMemberWhere[Q](buildCircleMemberColumns(alias))
}

func buildCircleMemberWhere[Q psql.Filterable](cols circleMemberColumns) circleMemberWhere[Q] {
	return circleMemberWhere[Q]{
		ID:        psql.Where[Q, uuid.UUID](cols.ID),
		CircleID:  psql.Where[Q, uuid.UUID](cols.CircleID),
		UserID:    psql.Where[Q, uuid.UUID](cols.UserID),
		Role:      psql.Where[Q, string](cols.Role),
		Nickname:  psql.WhereNull[Q, string](cols.Nickname),
		JoinedAt:  psql.Where[Q, time.Time](cols.JoinedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *CircleMember) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Circle":
		rel, ok := retrieved.(*Circle)
		if !ok {
			return fmt.Errorf("circleMember cannot load %T as %q", retrieved, name)
		}

		o.R.Circle = rel

		if rel != nil {
			rel.R.CircleMembers = CircleMemberSlice{o}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("circleMember cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.CircleMembers = CircleMemberSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("circleMember has no relationship %q", name)
	}
}

type circleMemberPreloader struct {
	Circle func(...psql.PreloadOption) psql.Preloader
	User   func(...psql.PreloadOption) psql.Preloader
}

func buildCircleMemberPreloader() circleMemberPreloader {
	return circleMemberPreloader{
		Circle: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Circle, CircleSlice](psql.PreloadRel{
				Name: "Circle",
				Sides: []psql.PreloadSide{
					{
						From:        CircleMembers,
						To:          Circles,
						FromColumns: []string{"circle_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Circles.Columns.Names(), opts...)
		},
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        CircleMembers,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type circleMemberThenLoader[Q orm.Loadable] struct {
	Circle func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildCircleMemberThenLoader[Q orm.Loadable]() circleMemberThenLoader[Q] {
	type CircleLoadInterface interface {
		LoadCircle(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return circleMemberThenLoader[Q]{
		Circle: thenLoadBuilder[Q](
			"Circle",
			func(ctx context.Context, exec bob.Executor, retrieved CircleLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCircle(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadCircle loads the circleMember's Circle into the .R struct
func (o *CircleMember) LoadCircle(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Circle = nil

	related, err := o.Circle(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.CircleMembers = CircleMemberSlice{o}

	o.R.Circle = related
	return nil
}

// LoadCircle loads the circleMember's Circle into the .R struct
func (os CircleMemberSlice) LoadCircle(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	circles, err := os.Circle(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range circles {

			if !(o.CircleID == rel.ID) {
				continue
			}

			rel.R.CircleMembers = append(rel.R.CircleMembers, o)

			o.R.Circle = rel
			break
		}
	}

	return nil
}

// LoadUser loads the circleMember's User into the .R struct
func (o *CircleMember) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.CircleMembers = CircleMemberSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the circleMember's User into the .R struct
func (os CircleMemberSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.CircleMembers = append(rel.R.CircleMembers, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type circleMemberJoins[Q dialect.Joinable] struct {
	typ    string
	Circle modAs[Q, circleColumns]
	User   modAs[Q, userColumns]
}

func (j circleMemberJoins[Q]) aliasedAs(alias string) circleMemberJoins[Q] {
	return buildCircleMemberJoins[Q](buildCircleMemberColumns(alias), j.typ)
}

func buildCircleMemberJoins[Q dialect.Joinable](cols circleMemberColumns, typ string) circleMemberJoins[Q] {
	return circleMemberJoins[Q]{
		typ: typ,
		Circle: modAs[Q, circleColumns]{
			c: Circles.Columns,
			f: func(to circleColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Circles.Name().As(to.Alias())).On(
						to.ID.EQ(cols.CircleID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
