// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// CircleInvitation is an object representing the database table.
type CircleInvitation struct {
	ID        uuid.UUID           `db:"id,pk" `
	CircleID  uuid.UUID           `db:"circle_id" `
	InviterID uuid.UUID           `db:"inviter_id" `
	InviteeID null.Val[uuid.UUID] `db:"invitee_id" `
	Type      string              `db:"type" `
	Code      string              `db:"code" `
	Status    string              `db:"status" `
	MaxUses   null.Val[int32]     `db:"max_uses" `
	UseCount  int32               `db:"use_count" `
	ExpiresAt null.Val[time.Time] `db:"expires_at" `
	CreatedAt time.Time           `db:"created_at" `
	UpdatedAt time.Time           `db:"updated_at" `

	R circleInvitationR `db:"-" `
}

// CircleInvitationSlice is an alias for a slice of pointers to CircleInvitation.
// This should almost always be used instead of []*CircleInvitation.
type CircleInvitationSlice []*CircleInvitation

// CircleInvitations contains methods to work with the circle_invitations table
var CircleInvitations = psql.NewTablex[*CircleInvitation, CircleInvitationSlice, *CircleInvitationSetter]("", "circle_invitations", buildCircleInvitationColumns("circle_invitations"))

// CircleInvitationsQuery is a query on the circle_invitations table
type CircleInvitationsQuery = *psql.ViewQuery[*CircleInvitation, CircleInvitationSlice]

// circleInvitationR is where relationships are stored.
type circleInvitationR struct {
	Circle      *Circle // circle_invitations.fk_circle_invitations_circle_id
	InviteeUser *User   // circle_invitations.fk_circle_invitations_invitee_id
	InviterUser *User   // circle_invitations.fk_circle_invitations_inviter_id
}

func buildCircleInvitationColumns(alias string) circleInvitationColumns {
	return circleInvitationColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "circle_id", "inviter_id", "invitee_id", "type", "code", "status", "max_uses", "use_count", "expires_at", "created_at", "updated_at",
		).WithParent("circle_invitations"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		CircleID:   psql.Quote(alias, "circle_id"),
		InviterID:  psql.Quote(alias, "inviter_id"),
		InviteeID:  psql.Quote(alias, "invitee_id"),
		Type:       psql.Quote(alias, "type"),
		Code:       psql.Quote(alias, "code"),
		Status:     psql.Quote(alias, "status"),
		MaxUses:    psql.Quote(alias, "max_uses"),
		UseCount:   psql.Quote(alias, "use_count"),
		ExpiresAt:  psql.Quote(alias, "expires_at"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type circleInvitationColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	CircleID   psql.Expression
	InviterID  psql.Expression
	InviteeID  psql.Expression
	Type       psql.Expression
	Code       psql.Expression
	Status     psql.Expression
	MaxUses    psql.Expression
	UseCount   psql.Expression
	ExpiresAt  psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c circleInvitationColumns) Alias() string {
	return c.tableAlias
}

func (circleInvitationColumns) AliasedAs(alias string) circleInvitationColumns {
	return buildCircleInvitationColumns(alias)
}

// CircleInvitationSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CircleInvitationSetter struct {
	ID        omit.Val[uuid.UUID]     `db:"id,pk" `
	CircleID  omit.Val[uuid.UUID]     `db:"circle_id" `
	InviterID omit.Val[uuid.UUID]     `db:"inviter_id" `
	InviteeID omitnull.Val[uuid.UUID] `db:"invitee_id" `
	Type      omit.Val[string]        `db:"type" `
	Code      omit.Val[string]        `db:"code" `
	Status    omit.Val[string]        `db:"status" `
	MaxUses   omitnull.Val[int32]     `db:"max_uses" `
	UseCount  omit.Val[int32]         `db:"use_count" `
	ExpiresAt omitnull.Val[time.Time] `db:"expires_at" `
	CreatedAt omit.Val[time.Time]     `db:"created_at" `
	UpdatedAt omit.Val[time.Time]     `db:"updated_at" `
}

func (s CircleInvitationSetter) SetColumns() []string {
	vals := make([]string, 0, 12)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.CircleID.IsValue() {
		vals = append(vals, "circle_id")
	}
	if s.InviterID.IsValue() {
		vals = append(vals, "inviter_id")
	}
	if !s.InviteeID.IsUnset() {
		vals = append(vals, "invitee_id")
	}
	if s.Type.IsValue() {
		vals = append(vals, "type")
	}
	if s.Code.IsValue() {
		vals = append(vals, "code")
	}
	if s.Status.IsValue() {
		vals = append(vals, "status")
	}
	if !s.MaxUses.IsUnset() {
		vals = append(vals, "max_uses")
	}
	if s.UseCount.IsValue() {
		vals = append(vals, "use_count")
	}
	if !s.ExpiresAt.IsUnset() {
		vals = append(vals, "expires_at")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s CircleInvitationSetter) Overwrite(t *CircleInvitation) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.CircleID.IsValue() {
		t.CircleID = s.CircleID.MustGet()
	}
	if s.InviterID.IsValue() {
		t.InviterID = s.InviterID.MustGet()
	}
	if !s.InviteeID.IsUnset() {
		t.InviteeID = s.InviteeID.MustGetNull()
	}
	if s.Type.IsValue() {
		t.Type = s.Type.MustGet()
	}
	if s.Code.IsValue() {
		t.Code = s.Code.MustGet()
	}
	if s.Status.IsValue() {
		t.Status = s.Status.MustGet()
	}
	if !s.MaxUses.IsUnset() {
		t.MaxUses = s.MaxUses.MustGetNull()
	}
	if s.UseCount.IsValue() {
		t.UseCount = s.UseCount.MustGet()
	}
	if !s.ExpiresAt.IsUnset() {
		t.ExpiresAt = s.ExpiresAt.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *CircleInvitationSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return CircleInvitations.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 12)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.CircleID.IsValue() {
			vals[1] = psql.Arg(s.CircleID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.InviterID.IsValue() {
			vals[2] = psql.Arg(s.InviterID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.InviteeID.IsUnset() {
			vals[3] = psql.Arg(s.InviteeID.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Type.IsValue() {
			vals[4] = psql.Arg(s.Type.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Code.IsValue() {
			vals[5] = psql.Arg(s.Code.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.Status.IsValue() {
			vals[6] = psql.Arg(s.Status.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.MaxUses.IsUnset() {
			vals[7] = psql.Arg(s.MaxUses.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.UseCount.IsValue() {
			vals[8] = psql.Arg(s.UseCount.MustGet())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if !s.ExpiresAt.IsUnset() {
			vals[9] = psql.Arg(s.ExpiresAt.MustGetNull())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[10] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[11] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s CircleInvitationSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s CircleInvitationSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 12)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.CircleID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "circle_id")...),
			psql.Arg(s.CircleID),
		}})
	}

	if s.InviterID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "inviter_id")...),
			psql.Arg(s.InviterID),
		}})
	}

	if !s.InviteeID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "invitee_id")...),
			psql.Arg(s.InviteeID),
		}})
	}

	if s.Type.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "type")...),
			psql.Arg(s.Type),
		}})
	}

	if s.Code.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "code")...),
			psql.Arg(s.Code),
		}})
	}

	if s.Status.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if !s.MaxUses.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "max_uses")...),
			psql.Arg(s.MaxUses),
		}})
	}

	if s.UseCount.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "use_count")...),
			psql.Arg(s.UseCount),
		}})
	}

	if !s.ExpiresAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "expires_at")...),
			psql.Arg(s.ExpiresAt),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindCircleInvitation retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCircleInvitation(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*CircleInvitation, error) {
	if len(cols) == 0 {
		return CircleInvitations.Query(
			sm.Where(CircleInvitations.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return CircleInvitations.Query(
		sm.Where(CircleInvitations.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(CircleInvitations.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CircleInvitationExists checks the presence of a single record by primary key
func CircleInvitationExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return CircleInvitations.Query(
		sm.Where(CircleInvitations.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after CircleInvitation is retrieved from the database
func (o *CircleInvitation) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CircleInvitations.AfterSelectHooks.RunHooks(ctx, exec, CircleInvitationSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = CircleInvitations.AfterInsertHooks.RunHooks(ctx, exec, CircleInvitationSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = CircleInvitations.AfterUpdateHooks.RunHooks(ctx, exec, CircleInvitationSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = CircleInvitations.AfterDeleteHooks.RunHooks(ctx, exec, CircleInvitationSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the CircleInvitation
func (o *CircleInvitation) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *CircleInvitation) pkEQ() dialect.Expression {
	return psql.Quote("circle_invitations", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the CircleInvitation
func (o *CircleInvitation) Update(ctx context.Context, exec bob.Executor, s *CircleInvitationSetter) error {
	v, err := CircleInvitations.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single CircleInvitation record with an executor
func (o *CircleInvitation) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := CircleInvitations.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the CircleInvitation using the executor
func (o *CircleInvitation) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := CircleInvitations.Query(
		sm.Where(CircleInvitations.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after CircleInvitationSlice is retrieved from the database
func (o CircleInvitationSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CircleInvitations.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = CircleInvitations.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = CircleInvitations.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = CircleInvitations.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CircleInvitationSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("circle_invitations", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CircleInvitationSlice) copyMatchingRows(from ...*CircleInvitation) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CircleInvitationSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return CircleInvitations.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *CircleInvitation:
				o.copyMatchingRows(retrieved)
			case []*CircleInvitation:
				o.copyMatchingRows(retrieved...)
			case CircleInvitationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a CircleInvitation or a slice of CircleInvitation
				// then run the AfterUpdateHooks on the slice
				_, err = CircleInvitations.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CircleInvitationSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return CircleInvitations.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *CircleInvitation:
				o.copyMatchingRows(retrieved)
			case []*CircleInvitation:
				o.copyMatchingRows(retrieved...)
			case CircleInvitationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a CircleInvitation or a slice of CircleInvitation
				// then run the AfterDeleteHooks on the slice
				_, err = CircleInvitations.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o CircleInvitationSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CircleInvitationSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := CircleInvitations.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o CircleInvitationSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := CircleInvitations.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CircleInvitationSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := CircleInvitations.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Circle starts a query for related objects on circles
func (o *CircleInvitation) Circle(mods ...bob.Mod[*dialect.SelectQuery]) CirclesQuery {
	return Circles.Query(append(mods,
		sm.Where(Circles.Columns.ID.EQ(psql.Arg(o.CircleID))),
	)...)
}

func (os CircleInvitationSlice) Circle(mods ...bob.Mod[*dialect.SelectQuery]) CirclesQuery {
	pkCircleID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkCircleID = append(pkCircleID, o.CircleID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkCircleID), "uuid[]")),
	))

	return Circles.Query(append(mods,
		sm.Where(psql.Group(Circles.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// InviteeUser starts a query for related objects on users
func (o *CircleInvitation) InviteeUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.InviteeID))),
	)...)
}

func (os CircleInvitationSlice) InviteeUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkInviteeID := make(pgtypes.Array[null.Val[uuid.UUID]], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkInviteeID = append(pkInviteeID, o.InviteeID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkInviteeID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// InviterUser starts a query for related objects on users
func (o *CircleInvitation) InviterUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.InviterID))),
	)...)
}

func (os CircleInvitationSlice) InviterUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkInviterID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkInviterID = append(pkInviterID, o.InviterID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkInviterID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachCircleInvitationCircle0(ctx context.Context, exec bob.Executor, count int, circleInvitation0 *CircleInvitation, circle1 *Circle) (*CircleInvitation, error) {
	setter := &CircleInvitationSetter{
		CircleID: omit.From(circle1.ID),
	}

	err := circleInvitation0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCircleInvitationCircle0: %w", err)
	}

	return circleInvitation0, nil
}

func (circleInvitation0 *CircleInvitation) InsertCircle(ctx context.Context, exec bob.Executor, related *CircleSetter) error {
	var err error

	circle1, err := Circles.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCircleInvitationCircle0(ctx, exec, 1, circleInvitation0, circle1)
	if err != nil {
		return err
	}

	circleInvitation0.R.Circle = circle1

	circle1.R.CircleInvitations = append(circle1.R.CircleInvitations, circleInvitation0)

	return nil
}

func (circleInvitation0 *CircleInvitation) AttachCircle(ctx context.Context, exec bob.Executor, circle1 *Circle) error {
	var err error

	_, err = attachCircleInvitationCircle0(ctx, exec, 1, circleInvitation0, circle1)
	if err != nil {
		return err
	}

	circleInvitation0.R.Circle = circle1

	circle1.R.CircleInvitations = append(circle1.R.CircleInvitations, circleInvitation0)

	return nil
}

func attachCircleInvitationInviteeUser0(ctx context.Context, exec bob.Executor, count int, circleInvitation0 *CircleInvitation, user1 *User) (*CircleInvitation, error) {
	setter := &CircleInvitationSetter{
		InviteeID: omitnull.From(user1.ID),
	}

	err := circleInvitation0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCircleInvitationInviteeUser0: %w", err)
	}

	return circleInvitation0, nil
}

func (circleInvitation0 *CircleInvitation) InsertInviteeUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCircleInvitationInviteeUser0(ctx, exec, 1, circleInvitation0, user1)
	if err != nil {
		return err
	}

	circleInvitation0.R.InviteeUser = user1

	user1.R.InviteeCircleInvitations = append(user1.R.InviteeCircleInvitations, circleInvitation0)

	return nil
}

func (circleInvitation0 *CircleInvitation) AttachInviteeUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachCircleInvitationInviteeUser0(ctx, exec, 1, circleInvitation0, user1)
	if err != nil {
		return err
	}

	circleInvitation0.R.InviteeUser = user1

	user1.R.InviteeCircleInvitations = append(user1.R.InviteeCircleInvitations, circleInvitation0)

	return nil
}

func attachCircleInvitationInviterUser0(ctx context.Context, exec bob.Executor, count int, circleInvitation0 *CircleInvitation, user1 *User) (*CircleInvitation, error) {
	setter := &CircleInvitationSetter{
		InviterID: omit.From(user1.ID),
	}

	err := circleInvitation0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCircleInvitationInviterUser0: %w", err)
	}

	return circleInvitation0, nil
}

func (circleInvitation0 *CircleInvitation) InsertInviterUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCircleInvitationInviterUser0(ctx, exec, 1, circleInvitation0, user1)
	if err != nil {
		return err
	}

	circleInvitation0.R.InviterUser = user1

	user1.R.InviterCircleInvitations = append(user1.R.InviterCircleInvitations, circleInvitation0)

	return nil
}

func (circleInvitation0 *CircleInvitation) AttachInviterUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachCircleInvitationInviterUser0(ctx, exec, 1, circleInvitation0, user1)
	if err != nil {
		return err
	}

	circleInvitation0.R.InviterUser = user1

	user1.R.InviterCircleInvitations = append(user1.R.InviterCircleInvitations, circleInvitation0)

	return nil
}

type circleInvitationWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, uuid.UUID]
	CircleID  psql.WhereMod[Q, uuid.UUID]
	InviterID psql.WhereMod[Q, uuid.UUID]
	InviteeID psql.WhereNullMod[Q, uuid.UUID]
	Type      psql.WhereMod[Q, string]
	Code      psql.WhereMod[Q, string]
	Status    psql.WhereMod[Q, string]
	MaxUses   psql.WhereNullMod[Q, int32]
	UseCount  psql.WhereMod[Q, int32]
	ExpiresAt psql.WhereNullMod[Q, time.Time]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (circleInvitationWhere[Q]) AliasedAs(alias string) circleInvitationWhere[Q] {
	return buildCircleInvitationWhere[Q](buildCircleInvitationColumns(alias))
}

func buildCircleInvitationWhere[Q psql.Filterable](cols circleInvitationColumns) circleInvitationWhere[Q] {
	return circleInvitationWhere[Q]{
		ID:        psql.Where[Q, uuid.UUID](cols.ID),
		CircleID:  psql.Where[Q, uuid.UUID](cols.CircleID),
		InviterID: psql.Where[Q, uuid.UUID](cols.InviterID),
		InviteeID: psql.WhereNull[Q, uuid.UUID](cols.InviteeID),
		Type:      psql.Where[Q, string](cols.Type),
		Code:      psql.Where[Q, string](cols.Code),
		Status:    psql.Where[Q, string](cols.Status),
		MaxUses:   psql.WhereNull[Q, int32](cols.MaxUses),
		UseCount:  psql.Where[Q, int32](cols.UseCount),
		ExpiresAt: psql.WhereNull[Q, time.Time](cols.ExpiresAt),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *CircleInvitation) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Circle":
		rel, ok := retrieved.(*Circle)
		if !ok {
			return fmt.Errorf("circleInvitation cannot load %T as %q", retrieved, name)
		}

		o.R.Circle = rel

		if rel != nil {
			rel.R.CircleInvitations = CircleInvitationSlice{o}
		}
		return nil
	case "InviteeUser":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("circleInvitation cannot load %T as %q", retrieved, name)
		}

		o.R.InviteeUser = rel

		if rel != nil {
			rel.R.InviteeCircleInvitations = CircleInvitationSlice{o}
		}
		return nil
	case "InviterUser":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("circleInvitation cannot load %T as %q", retrieved, name)
		}

		o.R.InviterUser = rel

		if rel != nil {
			rel.R.InviterCircleInvitations = CircleInvitationSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("circleInvitation has no relationship %q", name)
	}
}

type circleInvitationPreloader struct {
	Circle      func(...psql.PreloadOption) psql.Preloader
	InviteeUser func(...psql.PreloadOption) psql.Preloader
	InviterUser func(...psql.PreloadOption) psql.Preloader
}

func buildCircleInvitationPreloader() circleInvitationPreloader {
	return circleInvitationPreloader{
		Circle: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Circle, CircleSlice](psql.PreloadRel{
				Name: "Circle",
				Sides: []psql.PreloadSide{
					{
						From:        CircleInvitations,
						To:          Circles,
						FromColumns: []string{"circle_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Circles.Columns.Names(), opts...)
		},
		InviteeUser: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "InviteeUser",
				Sides: []psql.PreloadSide{
					{
						From:        CircleInvitations,
						To:          Users,
						FromColumns: []string{"invitee_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
		InviterUser: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "InviterUser",
				Sides: []psql.PreloadSide{
					{
						From:        CircleInvitations,
						To:          Users,
						FromColumns: []string{"inviter_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type circleInvitationThenLoader[Q orm.Loadable] struct {
	Circle      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	InviteeUser func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	InviterUser func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildCircleInvitationThenLoader[Q orm.Loadable]() circleInvitationThenLoader[Q] {
	type CircleLoadInterface interface {
		LoadCircle(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type InviteeUserLoadInterface interface {
		LoadInviteeUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type InviterUserLoadInterface interface {
		LoadInviterUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return circleInvitationThenLoader[Q]{
		Circle: thenLoadBuilder[Q](
			"Circle",
			func(ctx context.Context, exec bob.Executor, retrieved CircleLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCircle(ctx, exec, mods...)
			},
		),
		InviteeUser: thenLoadBuilder[Q](
			"InviteeUser",
			func(ctx context.Context, exec bob.Executor, retrieved InviteeUserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadInviteeUser(ctx, exec, mods...)
			},
		),
		InviterUser: thenLoadBuilder[Q](
			"InviterUser",
			func(ctx context.Context, exec bob.Executor, retrieved InviterUserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadInviterUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadCircle loads the circleInvitation's Circle into the .R struct
func (o *CircleInvitation) LoadCircle(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Circle = nil

	related, err := o.Circle(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.CircleInvitations = CircleInvitationSlice{o}

	o.R.Circle = related
	return nil
}

// LoadCircle loads the circleInvitation's Circle into the .R struct
func (os CircleInvitationSlice) LoadCircle(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	circles, err := os.Circle(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range circles {

			if !(o.CircleID == rel.ID) {
				continue
			}

			rel.R.CircleInvitations = append(rel.R.CircleInvitations, o)

			o.R.Circle = rel
			break
		}
	}

	return nil
}

// LoadInviteeUser loads the circleInvitation's InviteeUser into the .R struct
func (o *CircleInvitation) LoadInviteeUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.InviteeUser = nil

	related, err := o.InviteeUser(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.InviteeCircleInvitations = CircleInvitationSlice{o}

	o.R.InviteeUser = related
	return nil
}

// LoadInviteeUser loads the circleInvitation's InviteeUser into the .R struct
func (os CircleInvitationSlice) LoadInviteeUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.InviteeUser(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {
			if !o.InviteeID.IsValue() {
				continue
			}

			if !(o.InviteeID.IsValue() && o.InviteeID.MustGet() == rel.ID) {
				continue
			}

			rel.R.InviteeCircleInvitations = append(rel.R.InviteeCircleInvitations, o)

			o.R.InviteeUser = rel
			break
		}
	}

	return nil
}

// LoadInviterUser loads the circleInvitation's InviterUser into the .R struct
func (o *CircleInvitation) LoadInviterUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.InviterUser = nil

	related, err := o.InviterUser(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.InviterCircleInvitations = CircleInvitationSlice{o}

	o.R.InviterUser = related
	return nil
}

// LoadInviterUser loads the circleInvitation's InviterUser into the .R struct
func (os CircleInvitationSlice) LoadInviterUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.InviterUser(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.InviterID == rel.ID) {
				continue
			}

			rel.R.InviterCircleInvitations = append(rel.R.InviterCircleInvitations, o)

			o.R.InviterUser = rel
			break
		}
	}

	return nil
}

type circleInvitationJoins[Q dialect.Joinable] struct {
	typ         string
	Circle      modAs[Q, circleColumns]
	InviteeUser modAs[Q, userColumns]
	InviterUser modAs[Q, userColumns]
}

func (j circleInvitationJoins[Q]) aliasedAs(alias string) circleInvitationJoins[Q] {
	return buildCircleInvitationJoins[Q](buildCircleInvitationColumns(alias), j.typ)
}

func buildCircleInvitationJoins[Q dialect.Joinable](cols circleInvitationColumns, typ string) circleInvitationJoins[Q] {
	return circleInvitationJoins[Q]{
		typ: typ,
		Circle: modAs[Q, circleColumns]{
			c: Circles.Columns,
			f: func(to circleColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Circles.Name().As(to.Alias())).On(
						to.ID.EQ(cols.CircleID),
					))
				}

				return mods
			},
		},
		InviteeUser: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.InviteeID),
					))
				}

				return mods
			},
		},
		InviterUser: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.InviterID),
					))
				}

				return mods
			},
		},
	}
}
