// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Contact is an object representing the database table.
type Contact struct {
	ID         uuid.UUID        `db:"id,pk" `
	UserID     uuid.UUID        `db:"user_id" `
	ContactID  uuid.UUID        `db:"contact_id" `
	Nickname   null.Val[string] `db:"nickname" `
	IsFavorite bool             `db:"is_favorite" `
	IsBlocked  bool             `db:"is_blocked" `
	CreatedAt  time.Time        `db:"created_at" `
	UpdatedAt  time.Time        `db:"updated_at" `

	R contactR `db:"-" `
}

// ContactSlice is an alias for a slice of pointers to Contact.
// This should almost always be used instead of []*Contact.
type ContactSlice []*Contact

// Contacts contains methods to work with the contacts table
var Contacts = psql.NewTablex[*Contact, ContactSlice, *ContactSetter]("", "contacts", buildContactColumns("contacts"))

// ContactsQuery is a query on the contacts table
type ContactsQuery = *psql.ViewQuery[*Contact, ContactSlice]

// contactR is where relationships are stored.
type contactR struct {
	ContactUser *User // contacts.fk_contacts_contact_id
	User        *User // contacts.fk_contacts_user_id
}

func buildContactColumns(alias string) contactColumns {
	return contactColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "contact_id", "nickname", "is_favorite", "is_blocked", "created_at", "updated_at",
		).WithParent("contacts"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		UserID:     psql.Quote(alias, "user_id"),
		ContactID:  psql.Quote(alias, "contact_id"),
		Nickname:   psql.Quote(alias, "nickname"),
		IsFavorite: psql.Quote(alias, "is_favorite"),
		IsBlocked:  psql.Quote(alias, "is_blocked"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type contactColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	UserID     psql.Expression
	ContactID  psql.Expression
	Nickname   psql.Expression
	IsFavorite psql.Expression
	IsBlocked  psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c contactColumns) Alias() string {
	return c.tableAlias
}

func (contactColumns) AliasedAs(alias string) contactColumns {
	return buildContactColumns(alias)
}

// ContactSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ContactSetter struct {
	ID         omit.Val[uuid.UUID]  `db:"id,pk" `
	UserID     omit.Val[uuid.UUID]  `db:"user_id" `
	ContactID  omit.Val[uuid.UUID]  `db:"contact_id" `
	Nickname   omitnull.Val[string] `db:"nickname" `
	IsFavorite omit.Val[bool]       `db:"is_favorite" `
	IsBlocked  omit.Val[bool]       `db:"is_blocked" `
	CreatedAt  omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt  omit.Val[time.Time]  `db:"updated_at" `
}

func (s ContactSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.ContactID.IsValue() {
		vals = append(vals, "contact_id")
	}
	if !s.Nickname.IsUnset() {
		vals = append(vals, "nickname")
	}
	if s.IsFavorite.IsValue() {
		vals = append(vals, "is_favorite")
	}
	if s.IsBlocked.IsValue() {
		vals = append(vals, "is_blocked")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ContactSetter) Overwrite(t *Contact) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.ContactID.IsValue() {
		t.ContactID = s.ContactID.MustGet()
	}
	if !s.Nickname.IsUnset() {
		t.Nickname = s.Nickname.MustGetNull()
	}
	if s.IsFavorite.IsValue() {
		t.IsFavorite = s.IsFavorite.MustGet()
	}
	if s.IsBlocked.IsValue() {
		t.IsBlocked = s.IsBlocked.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *ContactSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Contacts.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.ContactID.IsValue() {
			vals[2] = psql.Arg(s.ContactID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.Nickname.IsUnset() {
			vals[3] = psql.Arg(s.Nickname.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.IsFavorite.IsValue() {
			vals[4] = psql.Arg(s.IsFavorite.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.IsBlocked.IsValue() {
			vals[5] = psql.Arg(s.IsBlocked.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[6] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[7] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ContactSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ContactSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.ContactID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "contact_id")...),
			psql.Arg(s.ContactID),
		}})
	}

	if !s.Nickname.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "nickname")...),
			psql.Arg(s.Nickname),
		}})
	}

	if s.IsFavorite.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_favorite")...),
			psql.Arg(s.IsFavorite),
		}})
	}

	if s.IsBlocked.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_blocked")...),
			psql.Arg(s.IsBlocked),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindContact retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindContact(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Contact, error) {
	if len(cols) == 0 {
		return Contacts.Query(
			sm.Where(Contacts.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Contacts.Query(
		sm.Where(Contacts.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Contacts.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ContactExists checks the presence of a single record by primary key
func ContactExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Contacts.Query(
		sm.Where(Contacts.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Contact is retrieved from the database
func (o *Contact) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Contacts.AfterSelectHooks.RunHooks(ctx, exec, ContactSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Contacts.AfterInsertHooks.RunHooks(ctx, exec, ContactSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Contacts.AfterUpdateHooks.RunHooks(ctx, exec, ContactSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Contacts.AfterDeleteHooks.RunHooks(ctx, exec, ContactSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Contact
func (o *Contact) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Contact) pkEQ() dialect.Expression {
	return psql.Quote("contacts", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Contact
func (o *Contact) Update(ctx context.Context, exec bob.Executor, s *ContactSetter) error {
	v, err := Contacts.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Contact record with an executor
func (o *Contact) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Contacts.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Contact using the executor
func (o *Contact) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Contacts.Query(
		sm.Where(Contacts.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ContactSlice is retrieved from the database
func (o ContactSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Contacts.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Contacts.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Contacts.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Contacts.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ContactSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("contacts", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ContactSlice) copyMatchingRows(from ...*Contact) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ContactSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Contacts.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Contact:
				o.copyMatchingRows(retrieved)
			case []*Contact:
				o.copyMatchingRows(retrieved...)
			case ContactSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Contact or a slice of Contact
				// then run the AfterUpdateHooks on the slice
				_, err = Contacts.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ContactSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Contacts.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Contact:
				o.copyMatchingRows(retrieved)
			case []*Contact:
				o.copyMatchingRows(retrieved...)
			case ContactSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Contact or a slice of Contact
				// then run the AfterDeleteHooks on the slice
				_, err = Contacts.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ContactSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ContactSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Contacts.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ContactSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Contacts.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ContactSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Contacts.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// ContactUser starts a query for related objects on users
func (o *Contact) ContactUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.ContactID))),
	)...)
}

func (os ContactSlice) ContactUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkContactID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkContactID = append(pkContactID, o.ContactID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkContactID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on users
func (o *Contact) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os ContactSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachContactContactUser0(ctx context.Context, exec bob.Executor, count int, contact0 *Contact, user1 *User) (*Contact, error) {
	setter := &ContactSetter{
		ContactID: omit.From(user1.ID),
	}

	err := contact0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachContactContactUser0: %w", err)
	}

	return contact0, nil
}

func (contact0 *Contact) InsertContactUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachContactContactUser0(ctx, exec, 1, contact0, user1)
	if err != nil {
		return err
	}

	contact0.R.ContactUser = user1

	user1.R.ContactContacts = append(user1.R.ContactContacts, contact0)

	return nil
}

func (contact0 *Contact) AttachContactUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachContactContactUser0(ctx, exec, 1, contact0, user1)
	if err != nil {
		return err
	}

	contact0.R.ContactUser = user1

	user1.R.ContactContacts = append(user1.R.ContactContacts, contact0)

	return nil
}

func attachContactUser0(ctx context.Context, exec bob.Executor, count int, contact0 *Contact, user1 *User) (*Contact, error) {
	setter := &ContactSetter{
		UserID: omit.From(user1.ID),
	}

	err := contact0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachContactUser0: %w", err)
	}

	return contact0, nil
}

func (contact0 *Contact) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachContactUser0(ctx, exec, 1, contact0, user1)
	if err != nil {
		return err
	}

	contact0.R.User = user1

	user1.R.Contacts = append(user1.R.Contacts, contact0)

	return nil
}

func (contact0 *Contact) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachContactUser0(ctx, exec, 1, contact0, user1)
	if err != nil {
		return err
	}

	contact0.R.User = user1

	user1.R.Contacts = append(user1.R.Contacts, contact0)

	return nil
}

type contactWhere[Q psql.Filterable] struct {
	ID         psql.WhereMod[Q, uuid.UUID]
	UserID     psql.WhereMod[Q, uuid.UUID]
	ContactID  psql.WhereMod[Q, uuid.UUID]
	Nickname   psql.WhereNullMod[Q, string]
	IsFavorite psql.WhereMod[Q, bool]
	IsBlocked  psql.WhereMod[Q, bool]
	CreatedAt  psql.WhereMod[Q, time.Time]
	UpdatedAt  psql.WhereMod[Q, time.Time]
}

func (contactWhere[Q]) AliasedAs(alias string) contactWhere[Q] {
	return buildContactWhere[Q](buildContactColumns(alias))
}

func buildContactWhere[Q psql.Filterable](cols contactColumns) contactWhere[Q] {
	return contactWhere[Q]{
		ID:         psql.Where[Q, uuid.UUID](cols.ID),
		UserID:     psql.Where[Q, uuid.UUID](cols.UserID),
		ContactID:  psql.Where[Q, uuid.UUID](cols.ContactID),
		Nickname:   psql.WhereNull[Q, string](cols.Nickname),
		IsFavorite: psql.Where[Q, bool](cols.IsFavorite),
		IsBlocked:  psql.Where[Q, bool](cols.IsBlocked),
		CreatedAt:  psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:  psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Contact) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "ContactUser":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("contact cannot load %T as %q", retrieved, name)
		}

		o.R.ContactUser = rel

		if rel != nil {
			rel.R.ContactContacts = ContactSlice{o}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("contact cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Contacts = ContactSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("contact has no relationship %q", name)
	}
}

type contactPreloader struct {
	ContactUser func(...psql.PreloadOption) psql.Preloader
	User        func(...psql.PreloadOption) psql.Preloader
}

func buildContactPreloader() contactPreloader {
	return contactPreloader{
		ContactUser: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "ContactUser",
				Sides: []psql.PreloadSide{
					{
						From:        Contacts,
						To:          Users,
						FromColumns: []string{"contact_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Contacts,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type contactThenLoader[Q orm.Loadable] struct {
	ContactUser func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildContactThenLoader[Q orm.Loadable]() contactThenLoader[Q] {
	type ContactUserLoadInterface interface {
		LoadContactUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return contactThenLoader[Q]{
		ContactUser: thenLoadBuilder[Q](
			"ContactUser",
			func(ctx context.Context, exec bob.Executor, retrieved ContactUserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadContactUser(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadContactUser loads the contact's ContactUser into the .R struct
func (o *Contact) LoadContactUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ContactUser = nil

	related, err := o.ContactUser(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.ContactContacts = ContactSlice{o}

	o.R.ContactUser = related
	return nil
}

// LoadContactUser loads the contact's ContactUser into the .R struct
func (os ContactSlice) LoadContactUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.ContactUser(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.ContactID == rel.ID) {
				continue
			}

			rel.R.ContactContacts = append(rel.R.ContactContacts, o)

			o.R.ContactUser = rel
			break
		}
	}

	return nil
}

// LoadUser loads the contact's User into the .R struct
func (o *Contact) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Contacts = ContactSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the contact's User into the .R struct
func (os ContactSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Contacts = append(rel.R.Contacts, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type contactJoins[Q dialect.Joinable] struct {
	typ         string
	ContactUser modAs[Q, userColumns]
	User        modAs[Q, userColumns]
}

func (j contactJoins[Q]) aliasedAs(alias string) contactJoins[Q] {
	return buildContactJoins[Q](buildContactColumns(alias), j.typ)
}

func buildContactJoins[Q dialect.Joinable](cols contactColumns, typ string) contactJoins[Q] {
	return contactJoins[Q]{
		typ: typ,
		ContactUser: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.ContactID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
