// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// ContactRequest is an object representing the database table.
type ContactRequest struct {
	ID         uuid.UUID        `db:"id,pk" `
	FromUserID uuid.UUID        `db:"from_user_id" `
	ToUserID   uuid.UUID        `db:"to_user_id" `
	Message    null.Val[string] `db:"message" `
	Status     string           `db:"status" `
	CreatedAt  time.Time        `db:"created_at" `
	UpdatedAt  time.Time        `db:"updated_at" `

	R contactRequestR `db:"-" `
}

// ContactRequestSlice is an alias for a slice of pointers to ContactRequest.
// This should almost always be used instead of []*ContactRequest.
type ContactRequestSlice []*ContactRequest

// ContactRequests contains methods to work with the contact_requests table
var ContactRequests = psql.NewTablex[*ContactRequest, ContactRequestSlice, *ContactRequestSetter]("", "contact_requests", buildContactRequestColumns("contact_requests"))

// ContactRequestsQuery is a query on the contact_requests table
type ContactRequestsQuery = *psql.ViewQuery[*ContactRequest, ContactRequestSlice]

// contactRequestR is where relationships are stored.
type contactRequestR struct {
	FromUserUser *User // contact_requests.fk_contact_requests_from_user_id
	ToUserUser   *User // contact_requests.fk_contact_requests_to_user_id
}

func buildContactRequestColumns(alias string) contactRequestColumns {
	return contactRequestColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "from_user_id", "to_user_id", "message", "status", "created_at", "updated_at",
		).WithParent("contact_requests"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		FromUserID: psql.Quote(alias, "from_user_id"),
		ToUserID:   psql.Quote(alias, "to_user_id"),
		Message:    psql.Quote(alias, "message"),
		Status:     psql.Quote(alias, "status"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type contactRequestColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	FromUserID psql.Expression
	ToUserID   psql.Expression
	Message    psql.Expression
	Status     psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c contactRequestColumns) Alias() string {
	return c.tableAlias
}

func (contactRequestColumns) AliasedAs(alias string) contactRequestColumns {
	return buildContactRequestColumns(alias)
}

// ContactRequestSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ContactRequestSetter struct {
	ID         omit.Val[uuid.UUID]  `db:"id,pk" `
	FromUserID omit.Val[uuid.UUID]  `db:"from_user_id" `
	ToUserID   omit.Val[uuid.UUID]  `db:"to_user_id" `
	Message    omitnull.Val[string] `db:"message" `
	Status     omit.Val[string]     `db:"status" `
	CreatedAt  omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt  omit.Val[time.Time]  `db:"updated_at" `
}

func (s ContactRequestSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.FromUserID.IsValue() {
		vals = append(vals, "from_user_id")
	}
	if s.ToUserID.IsValue() {
		vals = append(vals, "to_user_id")
	}
	if !s.Message.IsUnset() {
		vals = append(vals, "message")
	}
	if s.Status.IsValue() {
		vals = append(vals, "status")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ContactRequestSetter) Overwrite(t *ContactRequest) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.FromUserID.IsValue() {
		t.FromUserID = s.FromUserID.MustGet()
	}
	if s.ToUserID.IsValue() {
		t.ToUserID = s.ToUserID.MustGet()
	}
	if !s.Message.IsUnset() {
		t.Message = s.Message.MustGetNull()
	}
	if s.Status.IsValue() {
		t.Status = s.Status.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *ContactRequestSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ContactRequests.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 7)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.FromUserID.IsValue() {
			vals[1] = psql.Arg(s.FromUserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.ToUserID.IsValue() {
			vals[2] = psql.Arg(s.ToUserID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.Message.IsUnset() {
			vals[3] = psql.Arg(s.Message.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Status.IsValue() {
			vals[4] = psql.Arg(s.Status.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[5] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[6] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ContactRequestSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ContactRequestSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.FromUserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "from_user_id")...),
			psql.Arg(s.FromUserID),
		}})
	}

	if s.ToUserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "to_user_id")...),
			psql.Arg(s.ToUserID),
		}})
	}

	if !s.Message.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "message")...),
			psql.Arg(s.Message),
		}})
	}

	if s.Status.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindContactRequest retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindContactRequest(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*ContactRequest, error) {
	if len(cols) == 0 {
		return ContactRequests.Query(
			sm.Where(ContactRequests.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ContactRequests.Query(
		sm.Where(ContactRequests.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(ContactRequests.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ContactRequestExists checks the presence of a single record by primary key
func ContactRequestExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return ContactRequests.Query(
		sm.Where(ContactRequests.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ContactRequest is retrieved from the database
func (o *ContactRequest) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ContactRequests.AfterSelectHooks.RunHooks(ctx, exec, ContactRequestSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ContactRequests.AfterInsertHooks.RunHooks(ctx, exec, ContactRequestSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ContactRequests.AfterUpdateHooks.RunHooks(ctx, exec, ContactRequestSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ContactRequests.AfterDeleteHooks.RunHooks(ctx, exec, ContactRequestSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the ContactRequest
func (o *ContactRequest) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *ContactRequest) pkEQ() dialect.Expression {
	return psql.Quote("contact_requests", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ContactRequest
func (o *ContactRequest) Update(ctx context.Context, exec bob.Executor, s *ContactRequestSetter) error {
	v, err := ContactRequests.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single ContactRequest record with an executor
func (o *ContactRequest) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ContactRequests.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ContactRequest using the executor
func (o *ContactRequest) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ContactRequests.Query(
		sm.Where(ContactRequests.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ContactRequestSlice is retrieved from the database
func (o ContactRequestSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ContactRequests.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ContactRequests.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ContactRequests.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ContactRequests.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ContactRequestSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("contact_requests", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ContactRequestSlice) copyMatchingRows(from ...*ContactRequest) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ContactRequestSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ContactRequests.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ContactRequest:
				o.copyMatchingRows(retrieved)
			case []*ContactRequest:
				o.copyMatchingRows(retrieved...)
			case ContactRequestSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ContactRequest or a slice of ContactRequest
				// then run the AfterUpdateHooks on the slice
				_, err = ContactRequests.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ContactRequestSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ContactRequests.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ContactRequest:
				o.copyMatchingRows(retrieved)
			case []*ContactRequest:
				o.copyMatchingRows(retrieved...)
			case ContactRequestSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ContactRequest or a slice of ContactRequest
				// then run the AfterDeleteHooks on the slice
				_, err = ContactRequests.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ContactRequestSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ContactRequestSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ContactRequests.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ContactRequestSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ContactRequests.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ContactRequestSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ContactRequests.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// FromUserUser starts a query for related objects on users
func (o *ContactRequest) FromUserUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.FromUserID))),
	)...)
}

func (os ContactRequestSlice) FromUserUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkFromUserID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkFromUserID = append(pkFromUserID, o.FromUserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkFromUserID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// ToUserUser starts a query for related objects on users
func (o *ContactRequest) ToUserUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.ToUserID))),
	)...)
}

func (os ContactRequestSlice) ToUserUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkToUserID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkToUserID = append(pkToUserID, o.ToUserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkToUserID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachContactRequestFromUserUser0(ctx context.Context, exec bob.Executor, count int, contactRequest0 *ContactRequest, user1 *User) (*ContactRequest, error) {
	setter := &ContactRequestSetter{
		FromUserID: omit.From(user1.ID),
	}

	err := contactRequest0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachContactRequestFromUserUser0: %w", err)
	}

	return contactRequest0, nil
}

func (contactRequest0 *ContactRequest) InsertFromUserUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachContactRequestFromUserUser0(ctx, exec, 1, contactRequest0, user1)
	if err != nil {
		return err
	}

	contactRequest0.R.FromUserUser = user1

	user1.R.FromUserContactRequests = append(user1.R.FromUserContactRequests, contactRequest0)

	return nil
}

func (contactRequest0 *ContactRequest) AttachFromUserUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachContactRequestFromUserUser0(ctx, exec, 1, contactRequest0, user1)
	if err != nil {
		return err
	}

	contactRequest0.R.FromUserUser = user1

	user1.R.FromUserContactRequests = append(user1.R.FromUserContactRequests, contactRequest0)

	return nil
}

func attachContactRequestToUserUser0(ctx context.Context, exec bob.Executor, count int, contactRequest0 *ContactRequest, user1 *User) (*ContactRequest, error) {
	setter := &ContactRequestSetter{
		ToUserID: omit.From(user1.ID),
	}

	err := contactRequest0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachContactRequestToUserUser0: %w", err)
	}

	return contactRequest0, nil
}

func (contactRequest0 *ContactRequest) InsertToUserUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachContactRequestToUserUser0(ctx, exec, 1, contactRequest0, user1)
	if err != nil {
		return err
	}

	contactRequest0.R.ToUserUser = user1

	user1.R.ToUserContactRequests = append(user1.R.ToUserContactRequests, contactRequest0)

	return nil
}

func (contactRequest0 *ContactRequest) AttachToUserUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachContactRequestToUserUser0(ctx, exec, 1, contactRequest0, user1)
	if err != nil {
		return err
	}

	contactRequest0.R.ToUserUser = user1

	user1.R.ToUserContactRequests = append(user1.R.ToUserContactRequests, contactRequest0)

	return nil
}

type contactRequestWhere[Q psql.Filterable] struct {
	ID         psql.WhereMod[Q, uuid.UUID]
	FromUserID psql.WhereMod[Q, uuid.UUID]
	ToUserID   psql.WhereMod[Q, uuid.UUID]
	Message    psql.WhereNullMod[Q, string]
	Status     psql.WhereMod[Q, string]
	CreatedAt  psql.WhereMod[Q, time.Time]
	UpdatedAt  psql.WhereMod[Q, time.Time]
}

func (contactRequestWhere[Q]) AliasedAs(alias string) contactRequestWhere[Q] {
	return buildContactRequestWhere[Q](buildContactRequestColumns(alias))
}

func buildContactRequestWhere[Q psql.Filterable](cols contactRequestColumns) contactRequestWhere[Q] {
	return contactRequestWhere[Q]{
		ID:         psql.Where[Q, uuid.UUID](cols.ID),
		FromUserID: psql.Where[Q, uuid.UUID](cols.FromUserID),
		ToUserID:   psql.Where[Q, uuid.UUID](cols.ToUserID),
		Message:    psql.WhereNull[Q, string](cols.Message),
		Status:     psql.Where[Q, string](cols.Status),
		CreatedAt:  psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:  psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *ContactRequest) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "FromUserUser":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("contactRequest cannot load %T as %q", retrieved, name)
		}

		o.R.FromUserUser = rel

		if rel != nil {
			rel.R.FromUserContactRequests = ContactRequestSlice{o}
		}
		return nil
	case "ToUserUser":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("contactRequest cannot load %T as %q", retrieved, name)
		}

		o.R.ToUserUser = rel

		if rel != nil {
			rel.R.ToUserContactRequests = ContactRequestSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("contactRequest has no relationship %q", name)
	}
}

type contactRequestPreloader struct {
	FromUserUser func(...psql.PreloadOption) psql.Preloader
	ToUserUser   func(...psql.PreloadOption) psql.Preloader
}

func buildContactRequestPreloader() contactRequestPreloader {
	return contactRequestPreloader{
		FromUserUser: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "FromUserUser",
				Sides: []psql.PreloadSide{
					{
						From:        ContactRequests,
						To:          Users,
						FromColumns: []string{"from_user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
		ToUserUser: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "ToUserUser",
				Sides: []psql.PreloadSide{
					{
						From:        ContactRequests,
						To:          Users,
						FromColumns: []string{"to_user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type contactRequestThenLoader[Q orm.Loadable] struct {
	FromUserUser func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ToUserUser   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildContactRequestThenLoader[Q orm.Loadable]() contactRequestThenLoader[Q] {
	type FromUserUserLoadInterface interface {
		LoadFromUserUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ToUserUserLoadInterface interface {
		LoadToUserUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return contactRequestThenLoader[Q]{
		FromUserUser: thenLoadBuilder[Q](
			"FromUserUser",
			func(ctx context.Context, exec bob.Executor, retrieved FromUserUserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadFromUserUser(ctx, exec, mods...)
			},
		),
		ToUserUser: thenLoadBuilder[Q](
			"ToUserUser",
			func(ctx context.Context, exec bob.Executor, retrieved ToUserUserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadToUserUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadFromUserUser loads the contactRequest's FromUserUser into the .R struct
func (o *ContactRequest) LoadFromUserUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.FromUserUser = nil

	related, err := o.FromUserUser(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.FromUserContactRequests = ContactRequestSlice{o}

	o.R.FromUserUser = related
	return nil
}

// LoadFromUserUser loads the contactRequest's FromUserUser into the .R struct
func (os ContactRequestSlice) LoadFromUserUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.FromUserUser(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.FromUserID == rel.ID) {
				continue
			}

			rel.R.FromUserContactRequests = append(rel.R.FromUserContactRequests, o)

			o.R.FromUserUser = rel
			break
		}
	}

	return nil
}

// LoadToUserUser loads the contactRequest's ToUserUser into the .R struct
func (o *ContactRequest) LoadToUserUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ToUserUser = nil

	related, err := o.ToUserUser(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.ToUserContactRequests = ContactRequestSlice{o}

	o.R.ToUserUser = related
	return nil
}

// LoadToUserUser loads the contactRequest's ToUserUser into the .R struct
func (os ContactRequestSlice) LoadToUserUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.ToUserUser(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.ToUserID == rel.ID) {
				continue
			}

			rel.R.ToUserContactRequests = append(rel.R.ToUserContactRequests, o)

			o.R.ToUserUser = rel
			break
		}
	}

	return nil
}

type contactRequestJoins[Q dialect.Joinable] struct {
	typ          string
	FromUserUser modAs[Q, userColumns]
	ToUserUser   modAs[Q, userColumns]
}

func (j contactRequestJoins[Q]) aliasedAs(alias string) contactRequestJoins[Q] {
	return buildContactRequestJoins[Q](buildContactRequestColumns(alias), j.typ)
}

func buildContactRequestJoins[Q dialect.Joinable](cols contactRequestColumns, typ string) contactRequestJoins[Q] {
	return contactRequestJoins[Q]{
		typ: typ,
		FromUserUser: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.FromUserID),
					))
				}

				return mods
			},
		},
		ToUserUser: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.ToUserID),
					))
				}

				return mods
			},
		},
	}
}
