// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// ConversationParticipant is an object representing the database table.
type ConversationParticipant struct {
	ID             uuid.UUID           `db:"id,pk" `
	ConversationID uuid.UUID           `db:"conversation_id" `
	UserID         uuid.UUID           `db:"user_id" `
	IsMuted        bool                `db:"is_muted" `
	IsArchived     bool                `db:"is_archived" `
	LastReadAt     null.Val[time.Time] `db:"last_read_at" `
	JoinedAt       time.Time           `db:"joined_at" `
	LeftAt         null.Val[time.Time] `db:"left_at" `
	UpdatedAt      time.Time           `db:"updated_at" `

	R conversationParticipantR `db:"-" `
}

// ConversationParticipantSlice is an alias for a slice of pointers to ConversationParticipant.
// This should almost always be used instead of []*ConversationParticipant.
type ConversationParticipantSlice []*ConversationParticipant

// ConversationParticipants contains methods to work with the conversation_participants table
var ConversationParticipants = psql.NewTablex[*ConversationParticipant, ConversationParticipantSlice, *ConversationParticipantSetter]("", "conversation_participants", buildConversationParticipantColumns("conversation_participants"))

// ConversationParticipantsQuery is a query on the conversation_participants table
type ConversationParticipantsQuery = *psql.ViewQuery[*ConversationParticipant, ConversationParticipantSlice]

// conversationParticipantR is where relationships are stored.
type conversationParticipantR struct {
	Conversation *Conversation // conversation_participants.fk_conversation_participants_conversation_id
	User         *User         // conversation_participants.fk_conversation_participants_user_id
}

func buildConversationParticipantColumns(alias string) conversationParticipantColumns {
	return conversationParticipantColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "conversation_id", "user_id", "is_muted", "is_archived", "last_read_at", "joined_at", "left_at", "updated_at",
		).WithParent("conversation_participants"),
		tableAlias:     alias,
		ID:             psql.Quote(alias, "id"),
		ConversationID: psql.Quote(alias, "conversation_id"),
		UserID:         psql.Quote(alias, "user_id"),
		IsMuted:        psql.Quote(alias, "is_muted"),
		IsArchived:     psql.Quote(alias, "is_archived"),
		LastReadAt:     psql.Quote(alias, "last_read_at"),
		JoinedAt:       psql.Quote(alias, "joined_at"),
		LeftAt:         psql.Quote(alias, "left_at"),
		UpdatedAt:      psql.Quote(alias, "updated_at"),
	}
}

type conversationParticipantColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	ID             psql.Expression
	ConversationID psql.Expression
	UserID         psql.Expression
	IsMuted        psql.Expression
	IsArchived     psql.Expression
	LastReadAt     psql.Expression
	JoinedAt       psql.Expression
	LeftAt         psql.Expression
	UpdatedAt      psql.Expression
}

func (c conversationParticipantColumns) Alias() string {
	return c.tableAlias
}

func (conversationParticipantColumns) AliasedAs(alias string) conversationParticipantColumns {
	return buildConversationParticipantColumns(alias)
}

// ConversationParticipantSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ConversationParticipantSetter struct {
	ID             omit.Val[uuid.UUID]     `db:"id,pk" `
	ConversationID omit.Val[uuid.UUID]     `db:"conversation_id" `
	UserID         omit.Val[uuid.UUID]     `db:"user_id" `
	IsMuted        omit.Val[bool]          `db:"is_muted" `
	IsArchived     omit.Val[bool]          `db:"is_archived" `
	LastReadAt     omitnull.Val[time.Time] `db:"last_read_at" `
	JoinedAt       omit.Val[time.Time]     `db:"joined_at" `
	LeftAt         omitnull.Val[time.Time] `db:"left_at" `
	UpdatedAt      omit.Val[time.Time]     `db:"updated_at" `
}

func (s ConversationParticipantSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.ConversationID.IsValue() {
		vals = append(vals, "conversation_id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.IsMuted.IsValue() {
		vals = append(vals, "is_muted")
	}
	if s.IsArchived.IsValue() {
		vals = append(vals, "is_archived")
	}
	if !s.LastReadAt.IsUnset() {
		vals = append(vals, "last_read_at")
	}
	if s.JoinedAt.IsValue() {
		vals = append(vals, "joined_at")
	}
	if !s.LeftAt.IsUnset() {
		vals = append(vals, "left_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ConversationParticipantSetter) Overwrite(t *ConversationParticipant) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.ConversationID.IsValue() {
		t.ConversationID = s.ConversationID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.IsMuted.IsValue() {
		t.IsMuted = s.IsMuted.MustGet()
	}
	if s.IsArchived.IsValue() {
		t.IsArchived = s.IsArchived.MustGet()
	}
	if !s.LastReadAt.IsUnset() {
		t.LastReadAt = s.LastReadAt.MustGetNull()
	}
	if s.JoinedAt.IsValue() {
		t.JoinedAt = s.JoinedAt.MustGet()
	}
	if !s.LeftAt.IsUnset() {
		t.LeftAt = s.LeftAt.MustGetNull()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *ConversationParticipantSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ConversationParticipants.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 9)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.ConversationID.IsValue() {
			vals[1] = psql.Arg(s.ConversationID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[2] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.IsMuted.IsValue() {
			vals[3] = psql.Arg(s.IsMuted.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.IsArchived.IsValue() {
			vals[4] = psql.Arg(s.IsArchived.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.LastReadAt.IsUnset() {
			vals[5] = psql.Arg(s.LastReadAt.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.JoinedAt.IsValue() {
			vals[6] = psql.Arg(s.JoinedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.LeftAt.IsUnset() {
			vals[7] = psql.Arg(s.LeftAt.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[8] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ConversationParticipantSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ConversationParticipantSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.ConversationID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "conversation_id")...),
			psql.Arg(s.ConversationID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.IsMuted.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_muted")...),
			psql.Arg(s.IsMuted),
		}})
	}

	if s.IsArchived.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_archived")...),
			psql.Arg(s.IsArchived),
		}})
	}

	if !s.LastReadAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "last_read_at")...),
			psql.Arg(s.LastReadAt),
		}})
	}

	if s.JoinedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "joined_at")...),
			psql.Arg(s.JoinedAt),
		}})
	}

	if !s.LeftAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "left_at")...),
			psql.Arg(s.LeftAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindConversationParticipant retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindConversationParticipant(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*ConversationParticipant, error) {
	if len(cols) == 0 {
		return ConversationParticipants.Query(
			sm.Where(ConversationParticipants.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ConversationParticipants.Query(
		sm.Where(ConversationParticipants.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(ConversationParticipants.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ConversationParticipantExists checks the presence of a single record by primary key
func ConversationParticipantExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return ConversationParticipants.Query(
		sm.Where(ConversationParticipants.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ConversationParticipant is retrieved from the database
func (o *ConversationParticipant) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ConversationParticipants.AfterSelectHooks.RunHooks(ctx, exec, ConversationParticipantSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ConversationParticipants.AfterInsertHooks.RunHooks(ctx, exec, ConversationParticipantSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ConversationParticipants.AfterUpdateHooks.RunHooks(ctx, exec, ConversationParticipantSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ConversationParticipants.AfterDeleteHooks.RunHooks(ctx, exec, ConversationParticipantSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the ConversationParticipant
func (o *ConversationParticipant) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *ConversationParticipant) pkEQ() dialect.Expression {
	return psql.Quote("conversation_participants", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ConversationParticipant
func (o *ConversationParticipant) Update(ctx context.Context, exec bob.Executor, s *ConversationParticipantSetter) error {
	v, err := ConversationParticipants.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single ConversationParticipant record with an executor
func (o *ConversationParticipant) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ConversationParticipants.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ConversationParticipant using the executor
func (o *ConversationParticipant) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ConversationParticipants.Query(
		sm.Where(ConversationParticipants.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ConversationParticipantSlice is retrieved from the database
func (o ConversationParticipantSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ConversationParticipants.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ConversationParticipants.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ConversationParticipants.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ConversationParticipants.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ConversationParticipantSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("conversation_participants", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ConversationParticipantSlice) copyMatchingRows(from ...*ConversationParticipant) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ConversationParticipantSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ConversationParticipants.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ConversationParticipant:
				o.copyMatchingRows(retrieved)
			case []*ConversationParticipant:
				o.copyMatchingRows(retrieved...)
			case ConversationParticipantSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ConversationParticipant or a slice of ConversationParticipant
				// then run the AfterUpdateHooks on the slice
				_, err = ConversationParticipants.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ConversationParticipantSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ConversationParticipants.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ConversationParticipant:
				o.copyMatchingRows(retrieved)
			case []*ConversationParticipant:
				o.copyMatchingRows(retrieved...)
			case ConversationParticipantSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ConversationParticipant or a slice of ConversationParticipant
				// then run the AfterDeleteHooks on the slice
				_, err = ConversationParticipants.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ConversationParticipantSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ConversationParticipantSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ConversationParticipants.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ConversationParticipantSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ConversationParticipants.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ConversationParticipantSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ConversationParticipants.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Conversation starts a query for related objects on conversations
func (o *ConversationParticipant) Conversation(mods ...bob.Mod[*dialect.SelectQuery]) ConversationsQuery {
	return Conversations.Query(append(mods,
		sm.Where(Conversations.Columns.ID.EQ(psql.Arg(o.ConversationID))),
	)...)
}

func (os ConversationParticipantSlice) Conversation(mods ...bob.Mod[*dialect.SelectQuery]) ConversationsQuery {
	pkConversationID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkConversationID = append(pkConversationID, o.ConversationID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkConversationID), "uuid[]")),
	))

	return Conversations.Query(append(mods,
		sm.Where(psql.Group(Conversations.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on users
func (o *ConversationParticipant) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os ConversationParticipantSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachConversationParticipantConversation0(ctx context.Context, exec bob.Executor, count int, conversationParticipant0 *ConversationParticipant, conversation1 *Conversation) (*ConversationParticipant, error) {
	setter := &ConversationParticipantSetter{
		ConversationID: omit.From(conversation1.ID),
	}

	err := conversationParticipant0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachConversationParticipantConversation0: %w", err)
	}

	return conversationParticipant0, nil
}

func (conversationParticipant0 *ConversationParticipant) InsertConversation(ctx context.Context, exec bob.Executor, related *ConversationSetter) error {
	var err error

	conversation1, err := Conversations.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachConversationParticipantConversation0(ctx, exec, 1, conversationParticipant0, conversation1)
	if err != nil {
		return err
	}

	conversationParticipant0.R.Conversation = conversation1

	conversation1.R.ConversationParticipants = append(conversation1.R.ConversationParticipants, conversationParticipant0)

	return nil
}

func (conversationParticipant0 *ConversationParticipant) AttachConversation(ctx context.Context, exec bob.Executor, conversation1 *Conversation) error {
	var err error

	_, err = attachConversationParticipantConversation0(ctx, exec, 1, conversationParticipant0, conversation1)
	if err != nil {
		return err
	}

	conversationParticipant0.R.Conversation = conversation1

	conversation1.R.ConversationParticipants = append(conversation1.R.ConversationParticipants, conversationParticipant0)

	return nil
}

func attachConversationParticipantUser0(ctx context.Context, exec bob.Executor, count int, conversationParticipant0 *ConversationParticipant, user1 *User) (*ConversationParticipant, error) {
	setter := &ConversationParticipantSetter{
		UserID: omit.From(user1.ID),
	}

	err := conversationParticipant0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachConversationParticipantUser0: %w", err)
	}

	return conversationParticipant0, nil
}

func (conversationParticipant0 *ConversationParticipant) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachConversationParticipantUser0(ctx, exec, 1, conversationParticipant0, user1)
	if err != nil {
		return err
	}

	conversationParticipant0.R.User = user1

	user1.R.ConversationParticipants = append(user1.R.ConversationParticipants, conversationParticipant0)

	return nil
}

func (conversationParticipant0 *ConversationParticipant) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachConversationParticipantUser0(ctx, exec, 1, conversationParticipant0, user1)
	if err != nil {
		return err
	}

	conversationParticipant0.R.User = user1

	user1.R.ConversationParticipants = append(user1.R.ConversationParticipants, conversationParticipant0)

	return nil
}

type conversationParticipantWhere[Q psql.Filterable] struct {
	ID             psql.WhereMod[Q, uuid.UUID]
	ConversationID psql.WhereMod[Q, uuid.UUID]
	UserID         psql.WhereMod[Q, uuid.UUID]
	IsMuted        psql.WhereMod[Q, bool]
	IsArchived     psql.WhereMod[Q, bool]
	LastReadAt     psql.WhereNullMod[Q, time.Time]
	JoinedAt       psql.WhereMod[Q, time.Time]
	LeftAt         psql.WhereNullMod[Q, time.Time]
	UpdatedAt      psql.WhereMod[Q, time.Time]
}

func (conversationParticipantWhere[Q]) AliasedAs(alias string) conversationParticipantWhere[Q] {
	return buildConversationParticipantWhere[Q](buildConversationParticipantColumns(alias))
}

func buildConversationParticipantWhere[Q psql.Filterable](cols conversationParticipantColumns) conversationParticipantWhere[Q] {
	return conversationParticipantWhere[Q]{
		ID:             psql.Where[Q, uuid.UUID](cols.ID),
		ConversationID: psql.Where[Q, uuid.UUID](cols.ConversationID),
		UserID:         psql.Where[Q, uuid.UUID](cols.UserID),
		IsMuted:        psql.Where[Q, bool](cols.IsMuted),
		IsArchived:     psql.Where[Q, bool](cols.IsArchived),
		LastReadAt:     psql.WhereNull[Q, time.Time](cols.LastReadAt),
		JoinedAt:       psql.Where[Q, time.Time](cols.JoinedAt),
		LeftAt:         psql.WhereNull[Q, time.Time](cols.LeftAt),
		UpdatedAt:      psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *ConversationParticipant) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Conversation":
		rel, ok := retrieved.(*Conversation)
		if !ok {
			return fmt.Errorf("conversationParticipant cannot load %T as %q", retrieved, name)
		}

		o.R.Conversation = rel

		if rel != nil {
			rel.R.ConversationParticipants = ConversationParticipantSlice{o}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("conversationParticipant cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.ConversationParticipants = ConversationParticipantSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("conversationParticipant has no relationship %q", name)
	}
}

type conversationParticipantPreloader struct {
	Conversation func(...psql.PreloadOption) psql.Preloader
	User         func(...psql.PreloadOption) psql.Preloader
}

func buildConversationParticipantPreloader() conversationParticipantPreloader {
	return conversationParticipantPreloader{
		Conversation: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Conversation, ConversationSlice](psql.PreloadRel{
				Name: "Conversation",
				Sides: []psql.PreloadSide{
					{
						From:        ConversationParticipants,
						To:          Conversations,
						FromColumns: []string{"conversation_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Conversations.Columns.Names(), opts...)
		},
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        ConversationParticipants,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type conversationParticipantThenLoader[Q orm.Loadable] struct {
	Conversation func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User         func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildConversationParticipantThenLoader[Q orm.Loadable]() conversationParticipantThenLoader[Q] {
	type ConversationLoadInterface interface {
		LoadConversation(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return conversationParticipantThenLoader[Q]{
		Conversation: thenLoadBuilder[Q](
			"Conversation",
			func(ctx context.Context, exec bob.Executor, retrieved ConversationLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadConversation(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadConversation loads the conversationParticipant's Conversation into the .R struct
func (o *ConversationParticipant) LoadConversation(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Conversation = nil

	related, err := o.Conversation(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.ConversationParticipants = ConversationParticipantSlice{o}

	o.R.Conversation = related
	return nil
}

// LoadConversation loads the conversationParticipant's Conversation into the .R struct
func (os ConversationParticipantSlice) LoadConversation(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	conversations, err := os.Conversation(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range conversations {

			if !(o.ConversationID == rel.ID) {
				continue
			}

			rel.R.ConversationParticipants = append(rel.R.ConversationParticipants, o)

			o.R.Conversation = rel
			break
		}
	}

	return nil
}

// LoadUser loads the conversationParticipant's User into the .R struct
func (o *ConversationParticipant) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.ConversationParticipants = ConversationParticipantSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the conversationParticipant's User into the .R struct
func (os ConversationParticipantSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.ConversationParticipants = append(rel.R.ConversationParticipants, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type conversationParticipantJoins[Q dialect.Joinable] struct {
	typ          string
	Conversation modAs[Q, conversationColumns]
	User         modAs[Q, userColumns]
}

func (j conversationParticipantJoins[Q]) aliasedAs(alias string) conversationParticipantJoins[Q] {
	return buildConversationParticipantJoins[Q](buildConversationParticipantColumns(alias), j.typ)
}

func buildConversationParticipantJoins[Q dialect.Joinable](cols conversationParticipantColumns, typ string) conversationParticipantJoins[Q] {
	return conversationParticipantJoins[Q]{
		typ: typ,
		Conversation: modAs[Q, conversationColumns]{
			c: Conversations.Columns,
			f: func(to conversationColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Conversations.Name().As(to.Alias())).On(
						to.ID.EQ(cols.ConversationID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
