// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Place is an object representing the database table.
type Place struct {
	ID        uuid.UUID        `db:"id,pk" `
	UserID    uuid.UUID        `db:"user_id" `
	Name      string           `db:"name" `
	Type      string           `db:"type" `
	Latitude  float64          `db:"latitude" `
	Longitude float64          `db:"longitude" `
	Radius    float64          `db:"radius" `
	Address   null.Val[string] `db:"address" `
	Icon      null.Val[string] `db:"icon" `
	CreatedAt time.Time        `db:"created_at" `
	UpdatedAt time.Time        `db:"updated_at" `

	R placeR `db:"-" `
}

// PlaceSlice is an alias for a slice of pointers to Place.
// This should almost always be used instead of []*Place.
type PlaceSlice []*Place

// Places contains methods to work with the places table
var Places = psql.NewTablex[*Place, PlaceSlice, *PlaceSetter]("", "places", buildPlaceColumns("places"))

// PlacesQuery is a query on the places table
type PlacesQuery = *psql.ViewQuery[*Place, PlaceSlice]

// placeR is where relationships are stored.
type placeR struct {
	CheckIns CheckInSlice // check_ins.fk_check_ins_place_id
	User     *User        // places.fk_places_user_id
}

func buildPlaceColumns(alias string) placeColumns {
	return placeColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "name", "type", "latitude", "longitude", "radius", "address", "icon", "created_at", "updated_at",
		).WithParent("places"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		UserID:     psql.Quote(alias, "user_id"),
		Name:       psql.Quote(alias, "name"),
		Type:       psql.Quote(alias, "type"),
		Latitude:   psql.Quote(alias, "latitude"),
		Longitude:  psql.Quote(alias, "longitude"),
		Radius:     psql.Quote(alias, "radius"),
		Address:    psql.Quote(alias, "address"),
		Icon:       psql.Quote(alias, "icon"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type placeColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	UserID     psql.Expression
	Name       psql.Expression
	Type       psql.Expression
	Latitude   psql.Expression
	Longitude  psql.Expression
	Radius     psql.Expression
	Address    psql.Expression
	Icon       psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c placeColumns) Alias() string {
	return c.tableAlias
}

func (placeColumns) AliasedAs(alias string) placeColumns {
	return buildPlaceColumns(alias)
}

// PlaceSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PlaceSetter struct {
	ID        omit.Val[uuid.UUID]  `db:"id,pk" `
	UserID    omit.Val[uuid.UUID]  `db:"user_id" `
	Name      omit.Val[string]     `db:"name" `
	Type      omit.Val[string]     `db:"type" `
	Latitude  omit.Val[float64]    `db:"latitude" `
	Longitude omit.Val[float64]    `db:"longitude" `
	Radius    omit.Val[float64]    `db:"radius" `
	Address   omitnull.Val[string] `db:"address" `
	Icon      omitnull.Val[string] `db:"icon" `
	CreatedAt omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt omit.Val[time.Time]  `db:"updated_at" `
}

func (s PlaceSetter) SetColumns() []string {
	vals := make([]string, 0, 11)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Type.IsValue() {
		vals = append(vals, "type")
	}
	if s.Latitude.IsValue() {
		vals = append(vals, "latitude")
	}
	if s.Longitude.IsValue() {
		vals = append(vals, "longitude")
	}
	if s.Radius.IsValue() {
		vals = append(vals, "radius")
	}
	if !s.Address.IsUnset() {
		vals = append(vals, "address")
	}
	if !s.Icon.IsUnset() {
		vals = append(vals, "icon")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s PlaceSetter) Overwrite(t *Place) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Type.IsValue() {
		t.Type = s.Type.MustGet()
	}
	if s.Latitude.IsValue() {
		t.Latitude = s.Latitude.MustGet()
	}
	if s.Longitude.IsValue() {
		t.Longitude = s.Longitude.MustGet()
	}
	if s.Radius.IsValue() {
		t.Radius = s.Radius.MustGet()
	}
	if !s.Address.IsUnset() {
		t.Address = s.Address.MustGetNull()
	}
	if !s.Icon.IsUnset() {
		t.Icon = s.Icon.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *PlaceSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Places.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 11)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[2] = psql.Arg(s.Name.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Type.IsValue() {
			vals[3] = psql.Arg(s.Type.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Latitude.IsValue() {
			vals[4] = psql.Arg(s.Latitude.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Longitude.IsValue() {
			vals[5] = psql.Arg(s.Longitude.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.Radius.IsValue() {
			vals[6] = psql.Arg(s.Radius.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.Address.IsUnset() {
			vals[7] = psql.Arg(s.Address.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.Icon.IsUnset() {
			vals[8] = psql.Arg(s.Icon.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[9] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[10] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s PlaceSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s PlaceSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 11)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Type.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "type")...),
			psql.Arg(s.Type),
		}})
	}

	if s.Latitude.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "latitude")...),
			psql.Arg(s.Latitude),
		}})
	}

	if s.Longitude.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "longitude")...),
			psql.Arg(s.Longitude),
		}})
	}

	if s.Radius.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "radius")...),
			psql.Arg(s.Radius),
		}})
	}

	if !s.Address.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "address")...),
			psql.Arg(s.Address),
		}})
	}

	if !s.Icon.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "icon")...),
			psql.Arg(s.Icon),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindPlace retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPlace(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Place, error) {
	if len(cols) == 0 {
		return Places.Query(
			sm.Where(Places.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Places.Query(
		sm.Where(Places.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Places.Columns.Only(cols...)),
	).One(ctx, exec)
}

// PlaceExists checks the presence of a single record by primary key
func PlaceExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Places.Query(
		sm.Where(Places.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Place is retrieved from the database
func (o *Place) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Places.AfterSelectHooks.RunHooks(ctx, exec, PlaceSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Places.AfterInsertHooks.RunHooks(ctx, exec, PlaceSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Places.AfterUpdateHooks.RunHooks(ctx, exec, PlaceSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Places.AfterDeleteHooks.RunHooks(ctx, exec, PlaceSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Place
func (o *Place) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Place) pkEQ() dialect.Expression {
	return psql.Quote("places", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Place
func (o *Place) Update(ctx context.Context, exec bob.Executor, s *PlaceSetter) error {
	v, err := Places.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Place record with an executor
func (o *Place) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Places.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Place using the executor
func (o *Place) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Places.Query(
		sm.Where(Places.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after PlaceSlice is retrieved from the database
func (o PlaceSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Places.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Places.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Places.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Places.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PlaceSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("places", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PlaceSlice) copyMatchingRows(from ...*Place) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PlaceSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Places.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Place:
				o.copyMatchingRows(retrieved)
			case []*Place:
				o.copyMatchingRows(retrieved...)
			case PlaceSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Place or a slice of Place
				// then run the AfterUpdateHooks on the slice
				_, err = Places.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PlaceSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Places.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Place:
				o.copyMatchingRows(retrieved)
			case []*Place:
				o.copyMatchingRows(retrieved...)
			case PlaceSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Place or a slice of Place
				// then run the AfterDeleteHooks on the slice
				_, err = Places.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o PlaceSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PlaceSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Places.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o PlaceSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Places.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PlaceSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Places.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// CheckIns starts a query for related objects on check_ins
func (o *Place) CheckIns(mods ...bob.Mod[*dialect.SelectQuery]) CheckInsQuery {
	return CheckIns.Query(append(mods,
		sm.Where(CheckIns.Columns.PlaceID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os PlaceSlice) CheckIns(mods ...bob.Mod[*dialect.SelectQuery]) CheckInsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return CheckIns.Query(append(mods,
		sm.Where(psql.Group(CheckIns.Columns.PlaceID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on users
func (o *Place) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os PlaceSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertPlaceCheckIns0(ctx context.Context, exec bob.Executor, checkIns1 []*CheckInSetter, place0 *Place) (CheckInSlice, error) {
	for i := range checkIns1 {
		checkIns1[i].PlaceID = omit.From(place0.ID)
	}

	ret, err := CheckIns.Insert(bob.ToMods(checkIns1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertPlaceCheckIns0: %w", err)
	}

	return ret, nil
}

func attachPlaceCheckIns0(ctx context.Context, exec bob.Executor, count int, checkIns1 CheckInSlice, place0 *Place) (CheckInSlice, error) {
	setter := &CheckInSetter{
		PlaceID: omit.From(place0.ID),
	}

	err := checkIns1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachPlaceCheckIns0: %w", err)
	}

	return checkIns1, nil
}

func (place0 *Place) InsertCheckIns(ctx context.Context, exec bob.Executor, related ...*CheckInSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	checkIns1, err := insertPlaceCheckIns0(ctx, exec, related, place0)
	if err != nil {
		return err
	}

	place0.R.CheckIns = append(place0.R.CheckIns, checkIns1...)

	for _, rel := range checkIns1 {
		rel.R.Place = place0
	}
	return nil
}

func (place0 *Place) AttachCheckIns(ctx context.Context, exec bob.Executor, related ...*CheckIn) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	checkIns1 := CheckInSlice(related)

	_, err = attachPlaceCheckIns0(ctx, exec, len(related), checkIns1, place0)
	if err != nil {
		return err
	}

	place0.R.CheckIns = append(place0.R.CheckIns, checkIns1...)

	for _, rel := range related {
		rel.R.Place = place0
	}

	return nil
}

func attachPlaceUser0(ctx context.Context, exec bob.Executor, count int, place0 *Place, user1 *User) (*Place, error) {
	setter := &PlaceSetter{
		UserID: omit.From(user1.ID),
	}

	err := place0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachPlaceUser0: %w", err)
	}

	return place0, nil
}

func (place0 *Place) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachPlaceUser0(ctx, exec, 1, place0, user1)
	if err != nil {
		return err
	}

	place0.R.User = user1

	user1.R.Places = append(user1.R.Places, place0)

	return nil
}

func (place0 *Place) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachPlaceUser0(ctx, exec, 1, place0, user1)
	if err != nil {
		return err
	}

	place0.R.User = user1

	user1.R.Places = append(user1.R.Places, place0)

	return nil
}

type placeWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, uuid.UUID]
	UserID    psql.WhereMod[Q, uuid.UUID]
	Name      psql.WhereMod[Q, string]
	Type      psql.WhereMod[Q, string]
	Latitude  psql.WhereMod[Q, float64]
	Longitude psql.WhereMod[Q, float64]
	Radius    psql.WhereMod[Q, float64]
	Address   psql.WhereNullMod[Q, string]
	Icon      psql.WhereNullMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (placeWhere[Q]) AliasedAs(alias string) placeWhere[Q] {
	return buildPlaceWhere[Q](buildPlaceColumns(alias))
}

func buildPlaceWhere[Q psql.Filterable](cols placeColumns) placeWhere[Q] {
	return placeWhere[Q]{
		ID:        psql.Where[Q, uuid.UUID](cols.ID),
		UserID:    psql.Where[Q, uuid.UUID](cols.UserID),
		Name:      psql.Where[Q, string](cols.Name),
		Type:      psql.Where[Q, string](cols.Type),
		Latitude:  psql.Where[Q, float64](cols.Latitude),
		Longitude: psql.Where[Q, float64](cols.Longitude),
		Radius:    psql.Where[Q, float64](cols.Radius),
		Address:   psql.WhereNull[Q, string](cols.Address),
		Icon:      psql.WhereNull[Q, string](cols.Icon),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Place) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "CheckIns":
		rels, ok := retrieved.(CheckInSlice)
		if !ok {
			return fmt.Errorf("place cannot load %T as %q", retrieved, name)
		}

		o.R.CheckIns = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Place = o
			}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("place cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Places = PlaceSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("place has no relationship %q", name)
	}
}

type placePreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildPlacePreloader() placePreloader {
	return placePreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Places,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type placeThenLoader[Q orm.Loadable] struct {
	CheckIns func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildPlaceThenLoader[Q orm.Loadable]() placeThenLoader[Q] {
	type CheckInsLoadInterface interface {
		LoadCheckIns(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return placeThenLoader[Q]{
		CheckIns: thenLoadBuilder[Q](
			"CheckIns",
			func(ctx context.Context, exec bob.Executor, retrieved CheckInsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCheckIns(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadCheckIns loads the place's CheckIns into the .R struct
func (o *Place) LoadCheckIns(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CheckIns = nil

	related, err := o.CheckIns(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Place = o
	}

	o.R.CheckIns = related
	return nil
}

// LoadCheckIns loads the place's CheckIns into the .R struct
func (os PlaceSlice) LoadCheckIns(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	checkIns, err := os.CheckIns(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.CheckIns = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range checkIns {

			if !(o.ID == rel.PlaceID) {
				continue
			}

			rel.R.Place = o

			o.R.CheckIns = append(o.R.CheckIns, rel)
		}
	}

	return nil
}

// LoadUser loads the place's User into the .R struct
func (o *Place) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Places = PlaceSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the place's User into the .R struct
func (os PlaceSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Places = append(rel.R.Places, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type placeJoins[Q dialect.Joinable] struct {
	typ      string
	CheckIns modAs[Q, checkInColumns]
	User     modAs[Q, userColumns]
}

func (j placeJoins[Q]) aliasedAs(alias string) placeJoins[Q] {
	return buildPlaceJoins[Q](buildPlaceColumns(alias), j.typ)
}

func buildPlaceJoins[Q dialect.Joinable](cols placeColumns, typ string) placeJoins[Q] {
	return placeJoins[Q]{
		typ: typ,
		CheckIns: modAs[Q, checkInColumns]{
			c: CheckIns.Columns,
			f: func(to checkInColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, CheckIns.Name().As(to.Alias())).On(
						to.PlaceID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
