// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// UserLocation is an object representing the database table.
type UserLocation struct {
	UserID       uuid.UUID           `db:"user_id,pk" `
	Latitude     float64             `db:"latitude" `
	Longitude    float64             `db:"longitude" `
	Accuracy     null.Val[float64]   `db:"accuracy" `
	Altitude     null.Val[float64]   `db:"altitude" `
	Speed        null.Val[float64]   `db:"speed" `
	Heading      null.Val[float64]   `db:"heading" `
	PlaceID      null.Val[uuid.UUID] `db:"place_id" `
	Country      null.Val[string]    `db:"country" `
	City         null.Val[string]    `db:"city" `
	Neighborhood null.Val[string]    `db:"neighborhood" `
	Address      null.Val[string]    `db:"address" `
	IsMoving     bool                `db:"is_moving" `
	UpdatedAt    time.Time           `db:"updated_at" `

	R userLocationR `db:"-" `
}

// UserLocationSlice is an alias for a slice of pointers to UserLocation.
// This should almost always be used instead of []*UserLocation.
type UserLocationSlice []*UserLocation

// UserLocations contains methods to work with the user_locations table
var UserLocations = psql.NewTablex[*UserLocation, UserLocationSlice, *UserLocationSetter]("", "user_locations", buildUserLocationColumns("user_locations"))

// UserLocationsQuery is a query on the user_locations table
type UserLocationsQuery = *psql.ViewQuery[*UserLocation, UserLocationSlice]

// userLocationR is where relationships are stored.
type userLocationR struct {
	User *User // user_locations.fk_user_locations_user_id
}

func buildUserLocationColumns(alias string) userLocationColumns {
	return userLocationColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"user_id", "latitude", "longitude", "accuracy", "altitude", "speed", "heading", "place_id", "country", "city", "neighborhood", "address", "is_moving", "updated_at",
		).WithParent("user_locations"),
		tableAlias:   alias,
		UserID:       psql.Quote(alias, "user_id"),
		Latitude:     psql.Quote(alias, "latitude"),
		Longitude:    psql.Quote(alias, "longitude"),
		Accuracy:     psql.Quote(alias, "accuracy"),
		Altitude:     psql.Quote(alias, "altitude"),
		Speed:        psql.Quote(alias, "speed"),
		Heading:      psql.Quote(alias, "heading"),
		PlaceID:      psql.Quote(alias, "place_id"),
		Country:      psql.Quote(alias, "country"),
		City:         psql.Quote(alias, "city"),
		Neighborhood: psql.Quote(alias, "neighborhood"),
		Address:      psql.Quote(alias, "address"),
		IsMoving:     psql.Quote(alias, "is_moving"),
		UpdatedAt:    psql.Quote(alias, "updated_at"),
	}
}

type userLocationColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	UserID       psql.Expression
	Latitude     psql.Expression
	Longitude    psql.Expression
	Accuracy     psql.Expression
	Altitude     psql.Expression
	Speed        psql.Expression
	Heading      psql.Expression
	PlaceID      psql.Expression
	Country      psql.Expression
	City         psql.Expression
	Neighborhood psql.Expression
	Address      psql.Expression
	IsMoving     psql.Expression
	UpdatedAt    psql.Expression
}

func (c userLocationColumns) Alias() string {
	return c.tableAlias
}

func (userLocationColumns) AliasedAs(alias string) userLocationColumns {
	return buildUserLocationColumns(alias)
}

// UserLocationSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserLocationSetter struct {
	UserID       omit.Val[uuid.UUID]     `db:"user_id,pk" `
	Latitude     omit.Val[float64]       `db:"latitude" `
	Longitude    omit.Val[float64]       `db:"longitude" `
	Accuracy     omitnull.Val[float64]   `db:"accuracy" `
	Altitude     omitnull.Val[float64]   `db:"altitude" `
	Speed        omitnull.Val[float64]   `db:"speed" `
	Heading      omitnull.Val[float64]   `db:"heading" `
	PlaceID      omitnull.Val[uuid.UUID] `db:"place_id" `
	Country      omitnull.Val[string]    `db:"country" `
	City         omitnull.Val[string]    `db:"city" `
	Neighborhood omitnull.Val[string]    `db:"neighborhood" `
	Address      omitnull.Val[string]    `db:"address" `
	IsMoving     omit.Val[bool]          `db:"is_moving" `
	UpdatedAt    omit.Val[time.Time]     `db:"updated_at" `
}

func (s UserLocationSetter) SetColumns() []string {
	vals := make([]string, 0, 14)
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Latitude.IsValue() {
		vals = append(vals, "latitude")
	}
	if s.Longitude.IsValue() {
		vals = append(vals, "longitude")
	}
	if !s.Accuracy.IsUnset() {
		vals = append(vals, "accuracy")
	}
	if !s.Altitude.IsUnset() {
		vals = append(vals, "altitude")
	}
	if !s.Speed.IsUnset() {
		vals = append(vals, "speed")
	}
	if !s.Heading.IsUnset() {
		vals = append(vals, "heading")
	}
	if !s.PlaceID.IsUnset() {
		vals = append(vals, "place_id")
	}
	if !s.Country.IsUnset() {
		vals = append(vals, "country")
	}
	if !s.City.IsUnset() {
		vals = append(vals, "city")
	}
	if !s.Neighborhood.IsUnset() {
		vals = append(vals, "neighborhood")
	}
	if !s.Address.IsUnset() {
		vals = append(vals, "address")
	}
	if s.IsMoving.IsValue() {
		vals = append(vals, "is_moving")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s UserLocationSetter) Overwrite(t *UserLocation) {
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Latitude.IsValue() {
		t.Latitude = s.Latitude.MustGet()
	}
	if s.Longitude.IsValue() {
		t.Longitude = s.Longitude.MustGet()
	}
	if !s.Accuracy.IsUnset() {
		t.Accuracy = s.Accuracy.MustGetNull()
	}
	if !s.Altitude.IsUnset() {
		t.Altitude = s.Altitude.MustGetNull()
	}
	if !s.Speed.IsUnset() {
		t.Speed = s.Speed.MustGetNull()
	}
	if !s.Heading.IsUnset() {
		t.Heading = s.Heading.MustGetNull()
	}
	if !s.PlaceID.IsUnset() {
		t.PlaceID = s.PlaceID.MustGetNull()
	}
	if !s.Country.IsUnset() {
		t.Country = s.Country.MustGetNull()
	}
	if !s.City.IsUnset() {
		t.City = s.City.MustGetNull()
	}
	if !s.Neighborhood.IsUnset() {
		t.Neighborhood = s.Neighborhood.MustGetNull()
	}
	if !s.Address.IsUnset() {
		t.Address = s.Address.MustGetNull()
	}
	if s.IsMoving.IsValue() {
		t.IsMoving = s.IsMoving.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *UserLocationSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return UserLocations.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 14)
		if s.UserID.IsValue() {
			vals[0] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Latitude.IsValue() {
			vals[1] = psql.Arg(s.Latitude.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Longitude.IsValue() {
			vals[2] = psql.Arg(s.Longitude.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.Accuracy.IsUnset() {
			vals[3] = psql.Arg(s.Accuracy.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.Altitude.IsUnset() {
			vals[4] = psql.Arg(s.Altitude.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.Speed.IsUnset() {
			vals[5] = psql.Arg(s.Speed.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.Heading.IsUnset() {
			vals[6] = psql.Arg(s.Heading.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.PlaceID.IsUnset() {
			vals[7] = psql.Arg(s.PlaceID.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.Country.IsUnset() {
			vals[8] = psql.Arg(s.Country.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if !s.City.IsUnset() {
			vals[9] = psql.Arg(s.City.MustGetNull())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if !s.Neighborhood.IsUnset() {
			vals[10] = psql.Arg(s.Neighborhood.MustGetNull())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if !s.Address.IsUnset() {
			vals[11] = psql.Arg(s.Address.MustGetNull())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		if s.IsMoving.IsValue() {
			vals[12] = psql.Arg(s.IsMoving.MustGet())
		} else {
			vals[12] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[13] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[13] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserLocationSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserLocationSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 14)

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Latitude.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "latitude")...),
			psql.Arg(s.Latitude),
		}})
	}

	if s.Longitude.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "longitude")...),
			psql.Arg(s.Longitude),
		}})
	}

	if !s.Accuracy.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "accuracy")...),
			psql.Arg(s.Accuracy),
		}})
	}

	if !s.Altitude.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "altitude")...),
			psql.Arg(s.Altitude),
		}})
	}

	if !s.Speed.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "speed")...),
			psql.Arg(s.Speed),
		}})
	}

	if !s.Heading.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "heading")...),
			psql.Arg(s.Heading),
		}})
	}

	if !s.PlaceID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "place_id")...),
			psql.Arg(s.PlaceID),
		}})
	}

	if !s.Country.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "country")...),
			psql.Arg(s.Country),
		}})
	}

	if !s.City.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "city")...),
			psql.Arg(s.City),
		}})
	}

	if !s.Neighborhood.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "neighborhood")...),
			psql.Arg(s.Neighborhood),
		}})
	}

	if !s.Address.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "address")...),
			psql.Arg(s.Address),
		}})
	}

	if s.IsMoving.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_moving")...),
			psql.Arg(s.IsMoving),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindUserLocation retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUserLocation(ctx context.Context, exec bob.Executor, UserIDPK uuid.UUID, cols ...string) (*UserLocation, error) {
	if len(cols) == 0 {
		return UserLocations.Query(
			sm.Where(UserLocations.Columns.UserID.EQ(psql.Arg(UserIDPK))),
		).One(ctx, exec)
	}

	return UserLocations.Query(
		sm.Where(UserLocations.Columns.UserID.EQ(psql.Arg(UserIDPK))),
		sm.Columns(UserLocations.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UserLocationExists checks the presence of a single record by primary key
func UserLocationExists(ctx context.Context, exec bob.Executor, UserIDPK uuid.UUID) (bool, error) {
	return UserLocations.Query(
		sm.Where(UserLocations.Columns.UserID.EQ(psql.Arg(UserIDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after UserLocation is retrieved from the database
func (o *UserLocation) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UserLocations.AfterSelectHooks.RunHooks(ctx, exec, UserLocationSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = UserLocations.AfterInsertHooks.RunHooks(ctx, exec, UserLocationSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = UserLocations.AfterUpdateHooks.RunHooks(ctx, exec, UserLocationSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = UserLocations.AfterDeleteHooks.RunHooks(ctx, exec, UserLocationSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the UserLocation
func (o *UserLocation) primaryKeyVals() bob.Expression {
	return psql.Arg(o.UserID)
}

func (o *UserLocation) pkEQ() dialect.Expression {
	return psql.Quote("user_locations", "user_id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the UserLocation
func (o *UserLocation) Update(ctx context.Context, exec bob.Executor, s *UserLocationSetter) error {
	v, err := UserLocations.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single UserLocation record with an executor
func (o *UserLocation) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := UserLocations.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the UserLocation using the executor
func (o *UserLocation) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := UserLocations.Query(
		sm.Where(UserLocations.Columns.UserID.EQ(psql.Arg(o.UserID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserLocationSlice is retrieved from the database
func (o UserLocationSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UserLocations.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = UserLocations.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = UserLocations.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = UserLocations.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserLocationSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("user_locations", "user_id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserLocationSlice) copyMatchingRows(from ...*UserLocation) {
	for i, old := range o {
		for _, new := range from {
			if new.UserID != old.UserID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserLocationSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserLocations.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserLocation:
				o.copyMatchingRows(retrieved)
			case []*UserLocation:
				o.copyMatchingRows(retrieved...)
			case UserLocationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserLocation or a slice of UserLocation
				// then run the AfterUpdateHooks on the slice
				_, err = UserLocations.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserLocationSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserLocations.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserLocation:
				o.copyMatchingRows(retrieved)
			case []*UserLocation:
				o.copyMatchingRows(retrieved...)
			case UserLocationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserLocation or a slice of UserLocation
				// then run the AfterDeleteHooks on the slice
				_, err = UserLocations.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserLocationSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserLocationSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UserLocations.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserLocationSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UserLocations.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserLocationSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := UserLocations.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *UserLocation) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os UserLocationSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachUserLocationUser0(ctx context.Context, exec bob.Executor, count int, userLocation0 *UserLocation, user1 *User) (*UserLocation, error) {
	setter := &UserLocationSetter{
		UserID: omit.From(user1.ID),
	}

	err := userLocation0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserLocationUser0: %w", err)
	}

	return userLocation0, nil
}

func (userLocation0 *UserLocation) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserLocationUser0(ctx, exec, 1, userLocation0, user1)
	if err != nil {
		return err
	}

	userLocation0.R.User = user1

	user1.R.UserLocation = userLocation0

	return nil
}

func (userLocation0 *UserLocation) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachUserLocationUser0(ctx, exec, 1, userLocation0, user1)
	if err != nil {
		return err
	}

	userLocation0.R.User = user1

	user1.R.UserLocation = userLocation0

	return nil
}

type userLocationWhere[Q psql.Filterable] struct {
	UserID       psql.WhereMod[Q, uuid.UUID]
	Latitude     psql.WhereMod[Q, float64]
	Longitude    psql.WhereMod[Q, float64]
	Accuracy     psql.WhereNullMod[Q, float64]
	Altitude     psql.WhereNullMod[Q, float64]
	Speed        psql.WhereNullMod[Q, float64]
	Heading      psql.WhereNullMod[Q, float64]
	PlaceID      psql.WhereNullMod[Q, uuid.UUID]
	Country      psql.WhereNullMod[Q, string]
	City         psql.WhereNullMod[Q, string]
	Neighborhood psql.WhereNullMod[Q, string]
	Address      psql.WhereNullMod[Q, string]
	IsMoving     psql.WhereMod[Q, bool]
	UpdatedAt    psql.WhereMod[Q, time.Time]
}

func (userLocationWhere[Q]) AliasedAs(alias string) userLocationWhere[Q] {
	return buildUserLocationWhere[Q](buildUserLocationColumns(alias))
}

func buildUserLocationWhere[Q psql.Filterable](cols userLocationColumns) userLocationWhere[Q] {
	return userLocationWhere[Q]{
		UserID:       psql.Where[Q, uuid.UUID](cols.UserID),
		Latitude:     psql.Where[Q, float64](cols.Latitude),
		Longitude:    psql.Where[Q, float64](cols.Longitude),
		Accuracy:     psql.WhereNull[Q, float64](cols.Accuracy),
		Altitude:     psql.WhereNull[Q, float64](cols.Altitude),
		Speed:        psql.WhereNull[Q, float64](cols.Speed),
		Heading:      psql.WhereNull[Q, float64](cols.Heading),
		PlaceID:      psql.WhereNull[Q, uuid.UUID](cols.PlaceID),
		Country:      psql.WhereNull[Q, string](cols.Country),
		City:         psql.WhereNull[Q, string](cols.City),
		Neighborhood: psql.WhereNull[Q, string](cols.Neighborhood),
		Address:      psql.WhereNull[Q, string](cols.Address),
		IsMoving:     psql.Where[Q, bool](cols.IsMoving),
		UpdatedAt:    psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *UserLocation) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("userLocation cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.UserLocation = o
		}
		return nil
	default:
		return fmt.Errorf("userLocation has no relationship %q", name)
	}
}

type userLocationPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildUserLocationPreloader() userLocationPreloader {
	return userLocationPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        UserLocations,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type userLocationThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserLocationThenLoader[Q orm.Loadable]() userLocationThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userLocationThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the userLocation's User into the .R struct
func (o *UserLocation) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.UserLocation = o

	o.R.User = related
	return nil
}

// LoadUser loads the userLocation's User into the .R struct
func (os UserLocationSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.UserLocation = o

			o.R.User = rel
			break
		}
	}

	return nil
}

type userLocationJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j userLocationJoins[Q]) aliasedAs(alias string) userLocationJoins[Q] {
	return buildUserLocationJoins[Q](buildUserLocationColumns(alias), j.typ)
}

func buildUserLocationJoins[Q dialect.Joinable](cols userLocationColumns, typ string) userLocationJoins[Q] {
	return userLocationJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
